# -*- coding: utf-8 -*-
"""FineTuneBertInstead.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZrAslZhs83pOR9_bU1o1RrnMlmB989s
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install fpdf

'''
getting modified data
'''


import copy  #we are gonna need this bad boy right here
from datasets import Dataset
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
import torch
from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)
from torch.utils.data import DataLoader
from tqdm.auto import tqdm  #add progress bars
import os

def data_prepare():
  print("prepare data")
  #name of the multinli jsonl file
  file_name = "multinli_1.0_dev_matched.jsonl"
  path = "/content/drive/MyDrive/Colab Notebooks/DataforFineTuneBertInstead"
  #https://pandas.pydata.org/docs/reference/api/pandas.read_json.html  I can read this shit line by line with pandas

  entries_full = pd.read_json(path + '/' + file_name, lines = True, encoding = "utf-8")
  cols = entries_full.columns
  print(f"name of variables: {cols}")
  variables_needed = ['gold_label', 'sentence1', 'sentence2']

  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

  entries = entries_full[variables_needed].copy(deep=True)
  return entries


def tokenize(entries):
  print("tokenize")
  #https://stackoverflow.com/questions/73154119/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object
  dataset = Dataset.from_pandas(entries)
  #https://huggingface.co/docs/datasets/v1.8.0/processing.html
  tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

  #sentence1 = premise
  #sentence2 = hypothesis

  # This just sentence 1.
  def tokenize(batch):
      return tokenizer(
          batch["sentence1"],
          truncation=True,
          padding=False,
          max_length=128
      )

  #https://huggingface.co/docs/datasets/en/about_map_batch
  dataset = dataset.map(tokenize, batched=True)

  # set pytorch format:
  #columns = ["input_ids", "attention_mask", "token_type_ids", "label"]
  #dataset.set_format(type="torch")  #remove the columns
  #print("pytorch format made")

  print("done with tokenization")
  print(dataset["sentence1"])
  print(dataset["input_ids"])
  return dataset, tokenizer


def deswords_tok(tokenizer):
  words_to_remove = ["on top", "in front", "next to",
                      "in", "out", "over", "under", "above", "below", "inside",
                      "outside", "around", "behind", "on", "near", "through",
                      "throughout", "beneath", "into", "beside", "off", "between",
                      "next", "upon", "from"]

  words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False) for word in words_to_remove]
  print("Token Ids of words to remove: ", words_remove_tok_ids)
  return words_remove_tok_ids



def find(entries_tok_s1, to_remove):
  #the code here is halfway between psuedocode and real code it won't run yet.


  def contains_sequence(main_sequence, sub_sequence):
        n = len(sub_sequence)
        for i in range(len(main_sequence) - n + 1):
            if main_sequence[i:i+n] == sub_sequence:
                return True
        return False


  def filter_logic(data_set):
    input_ids = data_set['input_ids']
    for bad_word in to_remove:
      if contains_sequence(input_ids, bad_word):
        return True #keep row
    return False #no keep


  #https://huggingface.co/docs/datasets/en/process  #give it some logic and it'll filter rows based on that logic (whatever function you feed it)

  to_be_modified = entries_tok_s1.filter(filter_logic)

  print(len(entries_tok_s1))
  print(len(to_be_modified))

  return to_be_modified


def find_remove(entries_tok_s1, to_remove, tokenizer):

  #this only filters one entry in the full data set. So I gotta loop through this damn thing for each entry in the dingdang data set
    def filter_subseq(to_modify, to_remove):
      modified = [] #wwhere I save the shit
      n = len(to_remove) #this is not needed
      i = 0 #starts off at start at first token in our input string of tokens
      while i < len(to_modify):
        matched = False #reset at every removal
        for token in to_remove: #checks through every banned word in our list of word tokens to remove
          m = len(token) #sets the lengt to check to the end of the length of whatever current token string we are looking at
          if to_modify[i:i+m] == token: #if there is a matching token anywhere that looks like the token we want to remove #this gave a slice error because I tried to put an entire data set in here and not just a singular column so I ahve to change it up and add some filter logic with some batches
            matched = True #change the flag
            i += m #skip it matching token
            break #break the foor loop, but continue the while loop such that we keep checking the rest of the token string
        if not matched: #any token that is not on the banned word list enters the modified list, so banned words are excluded
          modified.append(to_modify[i])
          i += 1  #moves onto next token in string of tokens
      return modified

    #adding this filter logic function after spitballing with GeminiAI as it gave me a faster method to converting the filtered token strings back to words than what I had planned
    def filter_logic(batch):
      new_ids = filter_subseq(batch['input_ids'], to_remove)
      new_sentence = tokenizer.decode(new_ids, skip_special_tokens = True)  #<-- I am not sure if I want to skip these special tokens, unless they are recreated later in cell 2
      return {
          "input_ids" : new_ids, #I will end up deleting this column. But i'll save it for now just in case
          "sentence1" : new_sentence   #replaces the old sentence1 with the new sentence 1 that should be lacking prepositions
      }


    modified_dataset = entries_tok_s1.map(filter_logic)


    return modified_dataset


def drop_cols_i_hate(dataset):
  #https://huggingface.co/docs/datasets/v1.4.0/processing.html#removing-one-or-several-columns-remove-columns
  #there is a disgusting hair in my keyboard trying to slide under my spacebar
  dataset.remove_columns(["input_ids", "attention_mask", "token_type_ids"])
  return dataset


def save_data(modified, file_name):

  #make it pandas
  modified_df = modified.to_pandas()

  #file path
  folder_path = "/content/drive/MyDrive/Colab Notebooks/DataforFineTuneBertInstead"
  os.makedirs(folder_path, exist_ok=True) #makes the file directory if it don't exist
  file_path = os.path.join(folder_path, file_name + ".jsonl")

  #save it
  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html
  modified_df.to_json(file_path, orient = 'records', lines = True, force_ascii = False)
  #orient = records makes it so it is in the column, data in columns assorted by rows format. force ascii is false because I don't want to fuck anything up.

  print(f"saved at {file_path}")

  #https://stackoverflow.com/questions/77755675/how-to-convert-huggingface-datasets-to-json-and-vice-versa  <-- didn't do this

#silly me I forgot this very important step!
def make_copy_of_unmod(data_set):
  print("haodi")
  corresponding_unmodified_data = copy.deepcopy(data_set)
  return corresponding_unmodified_data



def main():
  print("main main")
  print("main")
  entries = data_prepare()
  #https://discuss.huggingface.co/t/from-pandas-dataframe-to-huggingface-dataset/9322
  #print(entries)
  #entries = filter_out_hyphen_labels(entries)
  #print(entries)
  #entries = gold_label_to_integers(entries)  <--- I actually don't want to get rid of hyphens or change labels to integers, since the next google colabs cell will do that.
  #print(entries)


  #entries_tok_s1 has the same data type as entries
  #convert sentence 1 to tokens
  entries_tok_s1, tokenizer = tokenize(entries)
  print(entries_tok_s1)
  print(type(entries_tok_s1))
  print(type(entries_tok_s1["input_ids"]))

  to_remove = deswords_tok(tokenizer)
  #identify sentence 1s with prepositions; save index number to later put sentence pairs + labels in their own data set
  #data types of to_be_modified is same as entries_tok_s1 (so it has all the columns, so data shouldn't get fucked up/missmapped)
  to_be_modified = find(entries_tok_s1, to_remove)
  #to_be_modified = we have a dataset of only the sentences with select words, but they have not been modified to remove them yet.
  corresponding_unmodified_set = make_copy_of_unmod(to_be_modified)

  #remove prepositions from that the sentence 1s that were confirmed to have prepositions
  #and deconverts sentence 1 back to regular sentence data
  #and puts the modified sentence 1 back into the running data set,
  #which means taking input_ids column, making changing it back to words,
  #shoving it into the sentence 1 column, and then delete the input_ids column to make space for it later,
  #data structure is still the same
  modified_s1 = find_remove(to_be_modified, to_remove, tokenizer)

  #the hugging face filter log

  #print(entries['sentence1'])
  #print(modified_s1["sentence1"])

  print(len(modified_s1)) #the hugging face filter logic prevents this from
  print(len(entries))

  len_mod = len(modified_s1)
  len_unmod = len(corresponding_unmodified_set)

  if len_mod != len_unmod:
    print("lenghts of data sets don't match, something is wrong")
    print(len_mod)
    print(len_unmod)
  else:
    print(len_mod)
    print(len_unmod)
    print("the lengths match")

  # and then delete the input_ids column to make space for it later
  modified_data = drop_cols_i_hate(modified_s1)
  unmodified_data = drop_cols_i_hate(corresponding_unmodified_set)
  save_data(modified_data, "modified_multinli_25preps")
  save_data(unmodified_data, "unmodified_multinli_25preps")


  #save it into google drive folder such that it can be called in other Google Colab Cell



if __name__ == "__main__":
  main()

'''
Kyle Urban Capstone
as of 1/13/2026 this is my most current issue https://stackoverflow.com/questions/43499199/tensorflow-loss-decreasing-but-accuracy-stable
loss drops from 1.20 to about 0.7 but accuracy never climbs higher than 0.34
We are trying one final time here completely fresh
1. run this on regular data set (small test)
2. run this on regular data set (full test)
3. run this on modified data set (full test)
4. compare results
'''
#https://huggingface.co/docs/datasets/en/about_map_batch

import gc
import random
from transformers import set_seed
from datetime import datetime
from datasets import Dataset
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
import torch
from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)
from torch.utils.data import DataLoader
from tqdm.auto import tqdm  #add progress bars
import os
from fpdf import FPDF #gonna make a pdf so I can print this.



def compute_metrics(eval_pred):
  #https://datascience.stackexchange.com/questions/31041/what-does-logits-in-machine-learning-mean
  #logits are like the last scores of the final layer of a model that decide the confidence of whether something is in one cateory or the other
  logits, labels  = eval_pred #unpack the tuple
  predictions = np.argmax(logits, axis=-1)  #this finds the most confident logit (highest/best prediction) of the last layer
  #the axis = -1 makes the damn thing look at the last layer https://stackoverflow.com/questions/73794766/what-is-the-meaning-of-axis-1-in-tf-keras-layers-normalization
  return {"accuracy": accuracy_score(labels, predictions)} #should give a column on data table (ngl I did steal this function from gemini)


def data_prepare(file_name):
  print("prepare data")
  #name of the multinli jsonl file
  path = "/content/drive/MyDrive/Colab Notebooks/DataforFineTuneBertInstead"
  #https://pandas.pydata.org/docs/reference/api/pandas.read_json.html  I can read this shit line by line with pandas

  entries_full = pd.read_json(path + '/' + file_name, lines = True, encoding = "utf-8")
  cols = entries_full.columns
  print(f"name of variables: {cols}")
  variables_needed = ['gold_label', 'sentence1', 'sentence2']

  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

  entries = entries_full[variables_needed].copy(deep=True)
  #print(entries)
  return entries

def filter_out_hyphen_labels(entries):
  #note that in the MultiNLI, there is a hyphen gold label as well
  print("filtering hyphens")
  #https://stackoverflow.com/questions/73907106/pandas-remove-every-entry-with-a-specific-value
  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop.html
  #https://pandas.pydata.org/docs/user_guide/indexing.html
  print("Unique labels found:", entries['gold_label'].unique())


  entries = entries[entries['gold_label'] != '-']
  return entries

def gold_label_to_integers(entries):
  print("map gold_labels to integers")
  label_map = {'entailment': 2, 'neutral': 1, 'contradiction': 0}
  entries['label'] = entries['gold_label'].map(label_map)

  #https://pandas.pydata.org/docs/reference/api/pandas.Index.dropna.html
  entries = entries.dropna(subset=['label'])
  #make sure every label is now an integer
  entries['label'] = entries['label'].astype(int)
  return entries

#so I need to save the original indicies
#so that with the train unmod set, I can pull them
#so I can remove them from them from the eval mod set (which ends up being from the whole set because there is no train_mod).
def save_og_indices(data_df):
  print("saving indices")
  data_df["original_index"] = data_df.index



def train_model(entries, num_train_epochs, logging_steps, num_layers_to_freeze, per_device_train_batch_size,
                per_device_eval_batch_size, skip_small, fp16, seed, weight_decay):
  print("experiment")

  #adds an extra column that saves the indices
  save_og_indices(entries)


  #https://stackoverflow.com/questions/73154119/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object
  dataset = Dataset.from_pandas(entries)


  dataset = dataset.train_test_split(test_size=0.1, seed = seed)
  train_dataset = dataset["train"]
  #I need to steal the train_indices from the train_dataset
  train_indices = train_dataset['original_index']
  eval_dataset = dataset["test"]
  print("train_test_split done")

  #https://huggingface.co/docs/datasets/v1.8.0/processing.html
  tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

  #sentence1 = premise
  #sentence2 = hypothesis

  # This concatenates sentence 1 and 2 as a single sequence before getting the CLS embedding.
  def tokenize(batch):
      return tokenizer(
          batch["sentence1"],
          batch["sentence2"],
          truncation=True,
          padding="max_length",
          max_length=128
      )

  #https://huggingface.co/docs/datasets/en/about_map_batch
  train_dataset = train_dataset.map(tokenize, batched=True)
  eval_dataset = eval_dataset.map(tokenize, batched=True)
  print("eval and train mapping done")


  # set pytorch format:
  columns = ["input_ids", "attention_mask", "token_type_ids", "label"]
  train_dataset.set_format(type="torch")  #remove the columns
  eval_dataset.set_format(type="torch")
  print("pytorch format made")




  # Now for fine-tuning bert:
  model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=3)
  print("model created")


  if num_layers_to_freeze != 0:
    print(f"IMMMMA FREEZIGN THE FIRST: {num_layers_to_freeze} layers")
    #Freeze bottom N encoder layers (e.g., first 8). This means only the last 4 layers of the model will update.
    for layer in model.bert.encoder.layer[:num_layers_to_freeze]:
      for param in layer.parameters():
        param.requires_grad = False
  else:
    print("no mom it's not cold outside I don't need a jacket")

  print("layers frozen")

  # Training configuration for colab:
  training_args = TrainingArguments(
      output_dir=f"./results_trial_{seed}",
      eval_strategy="epoch",   #evaluation_strategy got renamed to eval_strategy as per https://github.com/kubeflow/trainer/issues/2162
      save_strategy="epoch",
      learning_rate=2e-5,
      per_device_train_batch_size=per_device_train_batch_size,  #changing this to see what happens
      per_device_eval_batch_size=per_device_eval_batch_size,
      num_train_epochs=num_train_epochs,
      weight_decay=weight_decay,
      load_best_model_at_end= True,
      metric_for_best_model= "accuracy",
      save_total_limit = 2,
      #https://huggingface.co/docs/transformers/v5.0.0/en/main_classes/trainer#transformers.TrainingArguments
      logging_steps=logging_steps,
      fp16=fp16,  # works well on Colab GPUs allegedly #changing it to false #backt to true for full data set, back to false #back to true, toogle switch
      seed = seed,
      data_seed = seed,
      report_to="none")

  print("training args created")

  #https://huggingface.co/docs/transformers/en/main_classes/trainer
  #I can add a compute metrics thingy to this
  # Set up the trainer:
  trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_dataset,
      eval_dataset=eval_dataset,
      processing_class=tokenizer,    #had to change because "tokenizer" is now depreciated
      #https://stackoverflow.com/questions/79546910/typeerror-in-sfttrainer-initialization-unexpected-keyword-argument-tokenizer
      compute_metrics = compute_metrics
  )

  print("trainer created")
  print(train_dataset[0])

  print(entries[['gold_label','label']].head(20))
  print(entries['label'].value_counts())


  # Sanity check: ensure that you can overfit a small sample of the data.
  #https://huggingface.co/docs/transformers/en/main_classes/trainer
  # I can add metrics such as accuracy score to the trainer (thanks gemini)

  if skip_small == False:
    trainer.args.num_train_epochs = 50  # Force 50 epochs for the small test
    small_data_set_size = per_device_train_batch_size + 4

    small_train = train_dataset.shuffle(seed = seed).select(range(small_data_set_size)) #now we are shuffling the deck
    trainer.train_dataset = small_train
    trainer.eval_dataset = small_train #I am not sure how this acts as a sanity test
    trainer.train()
    results_small = trainer.evaluate()
    # If this gets close to 100% accuracy, then it's safe to continue. Otherwise there may be bugs.
    print("small sample set done")
    print(train_dataset[0]['label'], entries.iloc[0]['label'])
  else:
    print("small was skipped")
    small_data_set_size = 0
    #I have learned that skipping the overfit of the sample makes performance on the full data set worse. (but does it really? Or did I misread the data)

  #1/27/2026  it is possible to overfit the sample set. So we are gonna comment it out.

  # Restore full dataset if overfitting the small sample worked:
  trainer.args.num_train_epochs = num_train_epochs
  trainer.train_dataset = train_dataset
  trainer.eval_dataset = eval_dataset  #<--- forgot to add this (will need to rerun in the morning)
  results_train_full = trainer.train()
  results_full = trainer.evaluate()
  print("full set done")
  print(results_full)
  print(results_train_full)
  #print(train_dataset[0]['label'], entries.iloc[0]['label'])




  #return results_full, num_train_epochs, logging_steps, num_layers_to_freeze
  return trainer, results_full, results_train_full, small_data_set_size, train_indices

def pandas_to_hug(data_set):
  #https://stackoverflow.com/questions/73154119/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object
  dataset_hug = Dataset.from_pandas(data_set)
  return dataset_hug

def experiment(data, trainer, train_indices):

  #drop the train pairs used in unmod from the mod to prevent data leakage
  #data should be a pandas df here
  data = data.drop(train_indices)

  #converts the modified data set from a pandas df to a hugging face data set
  data = pandas_to_hug(data)

  #https://huggingface.co/docs/datasets/v1.8.0/processing.html
  tokenizer = trainer.processing_class

  #sentence1 = premise
  #sentence2 = hypothesis


  #gotta tokenize our modded stuff too... oops forgot to do that
  # This concatenates sentence 1 and 2 as a single sequence before getting the CLS embedding
  def tokenize(batch):
      return tokenizer(
          batch["sentence1"],
          batch["sentence2"],
          truncation=True,
          padding="max_length",
          max_length=128
      )

  data = data.map(tokenize, batched=True)

  #columns = ["input_ids", "attention_mask", "token_type_ids", "label"]
  data.set_format(type = "torch")

  model = trainer.model



  #eval the data set
  trainer.eval_dataset = data
  results = trainer.evaluate()


  return results


def results_file(trials_do, loss_avg_unmod, accu_avg_unmod, total_results_unmod, loss_avg_mod, accu_avg_mod, total_results_mod, num_train_epochs,
                 logging_steps, num_layers_to_freeze, per_device_train_batch_size, per_device_eval_batch_size, skip_small, file_name,
                 loss_avg_train, total_results_train, fp16, small_data_set_size, all_seeds):
  print("results to file")
  now = datetime.now()
  now_str = str(now)
  folder_path = "/content/drive/MyDrive/Colab Notebooks/DataFromFineTuneBertInstead"
  os.makedirs(folder_path, exist_ok = True) #makes the ding dang directory if I didn't already make it
  file_path = os.path.join(folder_path, file_name + now_str + ".txt")

  with open (file_path, 'w') as file:
    file.write(f"Time: {now_str}\n")
    file.write(f"Results of modified data eval\n")
    file.write(f"# of trials: {trials_do}\n")
    file.write(f"Avg accuracy across trials: {accu_avg_mod}\n")
    file.write(f"Avg loss across trials: {loss_avg_mod}\n")
    for i, result in enumerate(total_results_mod):
      file.write(f"Results from trial #{i + 1}:  {result} \n")

    file.write("\n______________________________________________\n")


    file.write(f"Results of unmodified data eval\n")
    file.write(f"# of trials: {trials_do}\n")
    file.write(f"Avg accuracy across trials: {accu_avg_unmod}\n")
    file.write(f"Avg loss across trials: {loss_avg_unmod}\n")
    for i, result in enumerate(total_results_unmod):
      file.write(f"Results from trial #{i + 1}:  {result} \n")

    file.write("\n_____________________________________________\n")

    file.write(f"Results of unmodified data training\n")
    file.write(f"# of trials: {trials_do}\n")
    file.write(f"Avg loss across trials: {loss_avg_train}\n")
    for i, result in enumerate(total_results_train):
      file.write(f"Results from trial #{i + 1}:  {result} \n")

    file.write("\n_____________________________________________\n")


    file.write(f"Additional Information over training on unmodified data: \n")
    file.write(f"number of epochs: {num_train_epochs}\n")
    file.write(f"logging steps: {logging_steps}\n")
    file.write(f"number of layers frozen: {num_layers_to_freeze}\n")
    file.write(f"per device train batch size: {per_device_train_batch_size}\n")
    file.write(f"per device eval batch size: {per_device_eval_batch_size}\n")
    file.write(f"fp16 status: {fp16}\n")

    if skip_small == False:
      status_skip = "no"
    else:
      status_skip = "yes"


    file.write(f"was small sample set (size {small_data_set_size}) training set skipped?:  {status_skip}\n")
    for i, seed in enumerate(all_seeds):
      file.write(f"For trial {i + 1}, the seed was {seed}\n")




    # {num_train_epochs, logging_steps, num_layers_to_freeze, per_device_train_batch_size, per_device_eval_batch_size, skip_small}")


def results_file_pdf(trials_do, loss_avg_unmod, accu_avg_unmod, total_results_unmod, loss_avg_mod, accu_avg_mod, total_results_mod, num_train_epochs,
                 logging_steps, num_layers_to_freeze, per_device_train_batch_size, per_device_eval_batch_size, skip_small, file_name,
                 loss_avg_train, total_results_train, fp16, small_data_set_size, all_seeds, weight_decay):
    print("gonna do pdf version")

  #this section was stolen from GeminiAI (I did not write this)
  # 1. Setup the PDF object (Portrait, millimeters, Letter size 8.5x11)
    pdf = FPDF(orientation='P', unit='mm', format='Letter')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Courier", size=10) # Courier mimics code/terminal look nicely

    # Helper function to write lines cleanly
    def write_line(text, bold=False):
        if bold:
            pdf.set_font("Courier", 'B', 10)
        else:
            pdf.set_font("Courier", '', 10)
        # Multi_cell handles text wrapping automatically
        pdf.multi_cell(0, 5, text)
        pdf.ln(1) # Add a small gap after lines

    # Helper for divider lines
    def write_divider():
        pdf.ln(2)
        pdf.line(pdf.get_x(), pdf.get_y(), 200, pdf.get_y()) # Draw visual line
        pdf.ln(4)


    def create_results_table(data_list, table_type):
        if not data_list:
            pdf.cell(0, 5, "No data available", ln=True)
            return

        # 1. DEFINE COLUMNS BASED ON TYPE
        if table_type == "eval":
            # (Header Name, Dictionary Key, Width)
            columns = [
                ("Trial",   None,       15),
                ("Loss",    "eval_loss", 25),
                ("Acc",     "eval_accuracy", 25),
                ("Runtime", "eval_runtime", 25),
                ("Samp/s",  "eval_samples_per_second", 25),
                ("Steps/s", "eval_steps_per_second", 25),
                ("Epoch",   "epoch",     20)
            ]
        elif table_type == "train":
            # Different keys for training data
            columns = [
                ("Trial",   None,       15),
                ("Loss",    "train_loss", 25),   # Key inside metrics
                ("Steps",   "global_step", 20),  # Key from object attribute
                ("Runtime", "train_runtime", 25),
                ("Samp/s",  "train_samples_per_second", 25),
                ("Steps/s", "train_steps_per_second", 25),
                ("Epoch",   "epoch",     20)
            ]

        # 2. Draw Header Row
        pdf.set_font("Helvetica", 'B', 8) # Smaller font for table
        for header, key, width in columns:
            pdf.cell(width, 6, header, border=1, align='C', fill=False)
        pdf.ln()

        # 3. Draw Data Rows
        pdf.set_font("Courier", '', 8)
        for i, raw_result in enumerate(data_list):

          # --- CRITICAL FIX: NORMALIZER LOGIC ---
            # This converts TrainOutput objects into dictionaries so .get() works
            row_dict = {}
            if hasattr(raw_result, 'metrics'): # Checks if it is a TrainOutput object
                row_dict = raw_result.metrics.copy()
                row_dict['global_step'] = raw_result.global_step
                row_dict['train_loss'] = raw_result.training_loss
                # Map specific keys if needed
                row_dict['train_runtime'] = row_dict.get('train_runtime')
                row_dict['train_samples_per_second'] = row_dict.get('train_samples_per_second')
                row_dict['train_steps_per_second'] = row_dict.get('train_steps_per_second')
            elif isinstance(raw_result, dict):
                row_dict = raw_result
            else:
                row_dict = {}
            # --------------------------------------

            # --- Column 1: Trial Number ---
            pdf.cell(columns[0][2], 6, str(i + 1), border=1, align='C')

            # --- Columns 2-7: Data from Dictionary ---
            for header, key, width in columns[1:]:
                # Get value safely (return '-' if missing)
                val = row_dict.get(key, '-')

                # Format numbers neatly if they are floats
                if isinstance(val, float):
                    val = f"{val:.4f}" # Round to 4 decimal places

                pdf.cell(width, 6, str(val), border=1, align='C')

            pdf.ln() # End of row
        pdf.ln(5) # Space after table


    #I did write this
    now = datetime.now()
    now_str = str(now)
    folder_path = "/content/drive/MyDrive/Colab Notebooks/DataFromFineTuneBertInstead"
    os.makedirs(folder_path, exist_ok = True) #makes the ding dang directory if I didn't already make it
    file_path = os.path.join(folder_path, file_name + now_str + ".pdf")

    #this was stolen from Gemini AI
    # 3. Write Content
    pdf.set_font("Courier", 'B', 14)
    pdf.cell(0, 10, "Training Results Report", ln=True, align='C')
    pdf.set_font("Courier", size=10)
    pdf.ln(5)

    # Header data
    write_line(f"Time: {now_str}\n")
    write_divider()

    # --- Modified Data Eval ---
    write_line("Results of MODIFIED data eval", bold=True)
    write_line(f"Trials: {trials_do}")
    write_line(f"Avg Accuracy: {accu_avg_mod}")  #<----- I had a giant ass typo right here.
    write_line(f"Avg Loss: {loss_avg_mod}")
    pdf.ln(2)
    create_results_table(total_results_mod, table_type = "eval")
    write_divider()

    # --- Unmodified Data Eval ---
    write_line("Results of UNMODIFIED data eval", bold=True)
    write_line(f"Trials: {trials_do}")
    write_line(f"Avg Accuracy: {accu_avg_unmod}")
    write_line(f"Avg Loss: {loss_avg_unmod}")
    pdf.ln(2)
    create_results_table(total_results_unmod, table_type = "eval")
    write_divider()

    # --- Unmodified Data Training ---
    write_line("Results of UNMODIFIED data training", bold=True)
    write_line(f"Trials: {trials_do}")
    write_line(f"Avg Loss: {loss_avg_train}")
    pdf.ln(2)
    create_results_table(total_results_train, table_type = "train")
    write_divider()

    # --- Hyperparameters ---
    write_line("Configuration & Hyperparameters", bold=True)
    write_line(f"Epochs: {num_train_epochs}")
    write_line(f"Logging Steps: {logging_steps}")
    write_line(f"Frozen Layers: {num_layers_to_freeze}")
    write_line(f"Train Batch Size: {per_device_train_batch_size}")
    write_line(f"Eval Batch Size: {per_device_eval_batch_size}")
    write_line(f"FP16 Status: {fp16}")
    write_line(f"weight_decay = {weight_decay}")

    if skip_small == False:
      status_skip = "no"
    else:
      status_skip = "yes"


    write_line(f"Small sample set skipped ({small_data_set_size}): {status_skip}")
    write_divider()
    for i, seed in enumerate(all_seeds):
      write_line(f"For trial {i+1}, seed was: {seed}")

    write_divider()
    write_line("fyi, I did have Gemini AI help me create the function to put my results in this PDF format")
    write_line("such that it would be more presentable compared to a .txt file")


    # 4. Save
    pdf.output(file_path)
    print(f"PDF saved to: {file_path}")



def trial_maker(unmod_data, mod_data, trials_do, num_train_epochs, logging_steps, num_layers_to_freeze,
                per_device_train_batch_size, per_device_eval_batch_size, skip_small, fp16, weight_decay, file_name):
  print("multiple_trials")
  #since the for loop in this function creates 10 models, I am going to need to clear up memory.
  total_results_mod = []
  tally_accu_mod = 0
  tally_loss_mod = 0

  total_results_unmod = []
  tally_accu_unmod = 0
  tally_loss_unmod = 0

  #remember, training is only done on the unmod
  total_results_train = []
  tally_accu_train = 0
  tally_loss_train = 0


  all_seeds = []


  for num_trials in range(1, trials_do + 1):
    # --- CRITICAL FIX: RESET SEEDS ---  added via gemini 2/4/26
    # Using a different seed for every trial ensures different initialization and shuffling
    current_seed = 42 + num_trials
    random.seed(current_seed)
    np.random.seed(current_seed)
    torch.manual_seed(current_seed)
    torch.cuda.manual_seed_all(current_seed)
    set_seed(current_seed) # Hugging Face specific seed setter

    all_seeds.append(current_seed)

    print(f"\n--- Starting Trial {num_trials} with Seed {current_seed} ---")

    #trains model on unmod and does its eval on unmod
    trainer, results_unmod, results_train, small_data_set_size, train_indices = train_model(unmod_data, num_train_epochs, logging_steps,
                                         num_layers_to_freeze, per_device_train_batch_size,
                                         per_device_eval_batch_size, skip_small, fp16, current_seed, weight_decay)
    total_results_unmod.append(results_unmod)
    tally_loss_unmod += results_unmod['eval_loss']
    tally_accu_unmod += results_unmod['eval_accuracy']

    #fyi train_indices are the indices of sentence pairs in the unmod that were used to train the model.
    #they must be used to purge those sentence pairs from the eval of the mod (to prevent data leakage!)

    total_results_train.append(results_train)
    tally_loss_train += results_train.metrics['train_loss']

    #evaluates on mod data
    results_mod = experiment(mod_data, trainer, train_indices)
    total_results_mod.append(results_mod)
    tally_loss_mod += results_mod['eval_loss']
    tally_accu_mod += results_mod['eval_accuracy']


    #save partial data incase of a crash

    loss_avg_mod_part = tally_loss_mod/num_trials
    accu_avg_mod_part= tally_accu_mod/num_trials

    loss_avg_unmod_part = tally_loss_unmod/num_trials
    accu_avg_unmod_part = tally_accu_unmod/num_trials

    loss_avg_train_part = tally_loss_train/num_trials

    num_trials_s = str(num_trials)
    trials_do_s = str(trials_do)

    part_name = "completed_" +  num_trials_s + "trials out of_" + trials_do_s + "____"

    results_file(num_trials, loss_avg_unmod_part, accu_avg_unmod_part, total_results_unmod, loss_avg_mod_part,
               accu_avg_mod_part, total_results_mod, num_train_epochs, logging_steps, num_layers_to_freeze,
               per_device_train_batch_size, per_device_eval_batch_size, skip_small, part_name,
               loss_avg_train_part, total_results_train, fp16, small_data_set_size, all_seeds)



    print(f"cleaning memory for trial {num_trials}")
    trainer.model.cpu()
    del trainer
    gc.collect()
    torch.cuda.synchronize() #add some waiting
    torch.cuda.empty_cache()
    print(f"Memory cleaned. GPU allocated: {torch.cuda.memory_allocated()}")


  loss_avg_mod = tally_loss_mod/trials_do
  accu_avg_mod = tally_accu_mod/trials_do

  loss_avg_unmod = tally_loss_unmod/trials_do
  accu_avg_unmod = tally_accu_unmod/trials_do

  loss_avg_train = tally_loss_train/trials_do

  results_file(trials_do, loss_avg_unmod, accu_avg_unmod, total_results_unmod, loss_avg_mod,
               accu_avg_mod, total_results_mod, num_train_epochs, logging_steps, num_layers_to_freeze,
               per_device_train_batch_size, per_device_eval_batch_size, skip_small, file_name,
               loss_avg_train, total_results_train, fp16, small_data_set_size, all_seeds)

  results_file_pdf(trials_do, loss_avg_unmod, accu_avg_unmod, total_results_unmod, loss_avg_mod,
               accu_avg_mod, total_results_mod, num_train_epochs, logging_steps, num_layers_to_freeze,
               per_device_train_batch_size, per_device_eval_batch_size, skip_small, file_name,
               loss_avg_train, total_results_train, fp16, small_data_set_size, all_seeds, weight_decay)

  return 1

def main():
  print("main")
  entries = data_prepare("unmodified_multinli_25preps.jsonl") #these two data sets should be the same size.
  entries_mod = data_prepare("modified_multinli_25preps.jsonl")
  #https://discuss.huggingface.co/t/from-pandas-dataframe-to-huggingface-dataset/9322
  entries = filter_out_hyphen_labels(entries)
  entries_mod = filter_out_hyphen_labels(entries_mod)
  entries = gold_label_to_integers(entries)
  entries_mod = gold_label_to_integers(entries_mod)
  print(len(entries))
  print(len(entries_mod))
  print(entries['sentence1'])
  print(entries_mod['sentence1'])
  current_path = "/content/drive/MyDrive/Colab Notebooks/DataforFineTuneBertInstead"


  trials_do = 10


  trial_maker(entries, entries_mod, trials_do, 4, 1, 0, 16, 16, True, True, 0.01, "results")
  trial_maker(entries, entries_mod, trials_do, 4, 1, 0, 16, 16, True, True, 0.1,  "results")
  trial_maker(entries, entries_mod, trials_do, 4, 1, 0, 16, 16, True, True, 0.3,  "results")
  trial_maker(entries, entries_mod, trials_do, 4, 1, 0, 16, 16, True, True, 0.5, "results")


  print("done")



if __name__ == "__main__":
  main()