# -*- coding: utf-8 -*-
"""GetCLSofJust2sets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9NLCRZO9GTk67ewB1ZYtsjri1476Gn9
"""

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*-
"""
Kyle Urban
University of Central Arkansas
Capstone File #0


"""
from dataclasses import dataclass
from copy import deepcopy
import pickle
import math
import torch  #May 31st, 2025 update, added in PyTorch cuz https://tenor.com/search/spongebob-i-need-it-gifs
import json
import os
import gc
import numpy as np #very important to the sanity check in part 2
import pandas as pd
#print(pd.__version__)
import tensorflow as tf
#print(tf.__version__)
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)  #Update as of 4/2/25 # 8/8 update, you hav eto use the from_pt = True now as Huggingface got an update

#move model onto GPU runtime to go faster (9/3/2025 update, ya' know ya boi got that google colabs pro)
''' #this is for pytorch only, tensorflow does this automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model.to(device)
'''
#check if Tensorflow is finding the GPU's

print(tf.config.list_physical_devices('GPU'))



# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


@dataclass
class Desword_Pairs:
  row_num: int
  sentence1_des: str
  sentence2_des: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  tensorized_s1: any = None
  tensorized_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None
  mask_s1: any = None
  mask_s2: any = None
  tokenized_joint: any = None
  tensorized_joint: any = None
  embed_joint: any = None
  last_hid_state_joint: any = None
  cls_embed_joint: any = None
  token_type_ids: any = None


  def __init__(self, row_num ,sentence1_des ,sentence2_des ,  gold_label , tokenized_s1 ,   tokenized_s2 ,
               flatten_tok_s1 ,  flatten_tok_s2 ,  pad_flat_tok_s1 ,  pad_flat_tok_s2 , tensorized_s1, tensorized_s2,
               pad_tensorized_s1 ,  pad_tensorized_s2 ,  embed_s1 ,  embed_s2 , last_hid_state_s1 ,
               last_hid_state_s2 ,  cls_embed_1 , cls_embed_2, mask_s1, mask_s2, tokenized_joint,
               tensorized_joint,embed_joint, last_hid_state_joint, cls_embed_joint, token_type_ids):
    self.row_num = row_num
    self.sentence1_des = sentence1_des
    self.sentence2_des = sentence2_des
    self.gold_label = gold_label
    self.tokenized_s1 = tokenized_s1
    self.tokenized_s2 = tokenized_s2
    self.flatten_tok_s1 = flatten_tok_s1
    self.flatten_tok_s2 = flatten_tok_s2
    self.pad_flat_tok_s1 = pad_flat_tok_s1
    self.pad_flat_tok_s2  = pad_flat_tok_s2
    self.tensorized_s1 = tensorized_s1
    self.tensorized_s2 = tensorized_s2
    self.pad_tensorized_s1 = pad_tensorized_s1
    self.pad_tensorized_s2  = pad_tensorized_s2
    self.embed_s1 = embed_s1
    self.embed_s2 = embed_s2
    self.last_hid_state_s1 = last_hid_state_s1
    self.last_hid_state_s2 = last_hid_state_s2
    self.cls_embed_1 = cls_embed_1
    self.cls_embed_2 = cls_embed_2
    self.mask_s1 = mask_s1
    self.mask_s2 = mask_s2
    self.tokenized_joint= tokenized_joint
    self.tensorized_joint= tensorized_joint
    self.embed_joint= embed_joint
    self.last_hid_state_joint= last_hid_state_joint
    self.cls_embed_joint= cls_embed_joint
    self.token_type_ids = token_type_ids


#the Desword_pair object also needs it own flatten to list obbject
#may not actually need this object
  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened

  def convert_back_to_tensors(self):
    print("takes flattened tensors and makes them unflat")

    self.tensorized_s1 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s1, dtype=tf.int32), (1, len(self.flatten_tok_s1)))
    self.tensorized_s2 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s2, dtype=tf.int32), (1, len(self.flatten_tok_s2)))


  def pad_tensors(self, max_seq_len_ten_s1, max_seq_len_ten_s2):
    print("post pads all my tensors")



    self.pad_tensorized_s1 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s1, maxlen = max_seq_len_ten_s1, padding = "post")
    self.pad_tensorized_s2 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s2, maxlen = max_seq_len_ten_s2, padding = "post")
    #https://www.tensorflow.org/api_docs/python/tf/keras/utils/pad_sequences
    #rework the code here to get a maximum lenght atwhich the sequences can be padded 8/24/2025

    print("row number: ", self.row_num)
    print("pad_tensorized_s1: ", self.pad_tensorized_s1)
    print("pad_tensorized_s2: " , self.pad_tensorized_s2)


  def get_shape_tok_s1(self):
    return self.tokenized_s1.shape

  def get_shape_tok_s2(self):
    return self.tokenized_s2.shape

  def get_shape_tensorized_s1(self):
    return self.tensorized_s1.shape

  def get_shape_tensorized_s2(self):
    return self.tensorized_s2.shape

  def get_shape_pad_ten_s1(self):
    return self.pad_tensorized_s1.shape

  def get_shape_pad_ten_s2(self):
    return self.pad_tensorized_s2.shape

  def get_last_hid_state_shape_s1(self):
    return self.last_hid_state_s1.shape

  def get_last_hid_state_shape_s2(self):
    return self.last_hid_state_s2.shape


#necesary for the word_search and removal method
  def copy_deep(self):
    return deepcopy(self)

  def word_search_and_remove(self, words_remove_tok_ids):
    print(self.row_num)

    #11/2/2025 update
    def remove_sequences_from_tokens(tokens, sequence):
      filtered = []
      i = 0
      while i < len(tokens):
        matched = False
        for seq in sequence:
          n = len(seq)
          if tokens[i:i+n] == seq:
            matched = True
            i += n #skips the sequence
            break
        if not matched:
          filtered.append(tokens[i])
          i += 1
      return filtered


    self_s1mod = self.copy_deep()
    self_s1mod.flatten_tok_s1 = remove_sequences_from_tokens(self.flatten_tok_s1, words_remove_tok_ids)

    '''
    self_s2mod = self.copy_deep()
    self_s2mod.flatten_tok_s2 = remove_sequences_from_tokens(self.flatten_tok_s2, words_remove_tok_ids)


    self_bothmod = self.copy_deep()
    self_bothmod.flatten_tok_s1 = remove_sequences_from_tokens(self.flatten_tok_s1, words_remove_tok_ids)
    self_bothmod.flatten_tok_s2 = remove_sequences_from_tokens(self.flatten_tok_s2, words_remove_tok_ids)
    '''

    return self_s1mod




    '''
    #gonna have to do this 3 times. Once for modifying the p/cs1, once for modifying the h/cs2, and then once for both modified
    #this should return 6 sets total I believe

    #in order to do this imma need to make deep copies of every self (every entry) 3 times inside here.

    #removing from the deep copied sets
    removal_set = set(words_remove_tok_ids)


    #https://realpython.com/python-enumerate/
    #https://www.w3schools.com/python/ref_list_pop.asp
    #https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
    #https://stackoverflow.com/questions/1207406/how-to-remove-items-from-a-list-while-iterating



    #Will the number of sentences that had a preposition removed be the same as the number of sentences that had a prepositions spotted?
    #go over your code logic with Dr Stine.


    #p' --> cs2 and cs1' --> h
    self_s1mod = self.copy_deep()
    self_s1mod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]


    #makes sense because when working cs1h, not all cs1s will have preps
    if (len(self_s1mod.flatten_tok_s1) == len(self.flatten_tok_s1)):
      print("len of s1  ")
      print(len(self.flatten_tok_s1))
      print("len of s1' ")
      print(len(self_s1mod.flatten_tok_s1))

    #p --> cs2' and cs1 --> h'
    self_s2mod = self.copy_deep()
    self_s2mod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]

    #makes sense because when working on pcs2, not all cs2s will have preps
    if (len(self_s2mod.flatten_tok_s2) == len(self.flatten_tok_s2)):
      print("len of s2  ")
      print(len(self.flatten_tok_s2))
      print("len of s2' ")
      print(len(self_s2mod.flatten_tok_s2))


    #p'--> cs2' and cs1' --> h'
    self_bothmod = self.copy_deep()
    self_bothmod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]
    self_bothmod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]




    '''




  def embed_the_padded_tensors(self):
    self.embed_s1 = bert_model(self.pad_tensorized_s1, attention_mask = self.mask_s1) #1/10/2026 addding in masks to not fuck up the data
    self.embed_s2 = bert_model(self.pad_tensorized_s2, attention_mask = self.mask_s2)

  def embed_joint_tensors(self):
    print("b") #it could be an issue of axis
    #http://tensorflow.org/guide/ragged_tensor
    #tensors can be ragged or dense, (models only accept dense) 1/11/2026 at 11:20pm
    self.tensorized_joint = self.tensorized_joint.to_tensor()
    self.embed_joint = bert_model(self.tensorized_joint, token_type_ids= self.token_type_ids.to_tensor()) #gonna try this 1/11/2026
    print("c")


  def last_hid_state_from_embed(self):

    self.last_hid_state_s1 = self.embed_s1.last_hidden_state
    self.last_hid_state_s2 = self.embed_s2.last_hidden_state  #there has been an error here for months, just now fixed 12/16/2025 @ 10:14pm

  def last_hid_state_from_embed_joint(self):
    self.last_hid_state_joint = self.embed_joint.last_hidden_state

  def cls_embed_from_last_hid_state(self):

    self.cls_embed_1 = self.last_hid_state_s1[:,0,:]
    self.cls_embed_2 = self.last_hid_state_s2[:,0,:]

  def cls_embed_from_last_hid_state_joint(self):
    self.cls_embed_joint = self.last_hid_state_joint[:,0,:]


  def get_cls_embeds_s1(self):
    return self.cls_embed_1

  def get_cls_embeds_s2(self):
    return self.cls_embed_2

  def get_cls_embeds_rownum(self):
    return self.row_num, self.cls_embed_1, self.cls_embed_2

  def attention_mask(self):
    mask_s1 = tf.cast(self.pad_tensorized_s1 != 0, tf.int32)
    mask_s2 = tf.cast(self.pad_tensorized_s2 != 0, tf.int32)

    return mask_s1, mask_s2

  def joint_maker(self):
    #print("trying to make the joint at the flattened token level")
    #I need to remove the CLS of tensorized_s2 before putting them together
    def remove_CLS_from_tensorized_s2():
      CLS_ID = 101
      #print("1")

      cls_tok_id = tf.constant(CLS_ID, dtype = tf.int32)
      #print("2")

      mask = tf.not_equal(self.tensorized_s2, cls_tok_id)
      #print("3")

      #https://www.tensorflow.org/api_docs/python/tf/ragged/boolean_mask supposedly this does masking without fuckign things up
      self.tensorized_s2 = tf.ragged.boolean_mask(self.tensorized_s2, mask)
      #print("4")


    remove_CLS_from_tensorized_s2()
    #http://tensorflow.org/api_docs/python/tf/zeros_like token type ids are needed for the model to know that the two sentences in the joint are supposed to be interpreted as separate sentences
    s1_types = tf.zeros_like(self.tensorized_s1)
    s2_types = tf.ones_like(self.tensorized_s2)
    self.token_type_ids = tf.concat([s1_types, s2_types], axis=1)
    #joint_tokens = (["[CLS]"] + sent_1_tokens + ["[SEP]"] + sent_2_tokens + ["[SEP]"])
    #print("5")
    #https://www.geeksforgeeks.org/deep-learning/tensor-concatenations-in-tensorflow-with-example/ gonna go with axis = 0 (well idk)
    #self.tensorized_joint = tf.concat([self.tensorized_s1, self.tensorized_s2], axis = 0) #idk which axis I should do
    self.tensorized_joint = tf.concat([self.tensorized_s1, self.tensorized_s2], axis = 1) #idk which axis I should do
    #print("6")








# ___________________________________________________________________________
# ___________________________________________________________________________
# __________________________________________________________________________



@dataclass #this makes the __init__ and __repr__ functions for me :)  (took this line from ChatGPT)
class MultiNLI_entry:
  row_num: int
  sentence1: str
  sentence2: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  tensorized_s1 : any = None
  tensorized_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None
  mask_s1: any = None
  mask_s2: any = None
  tokenized_joint: any = None
  tensorized_joint: any = None
  embed_joint: any = None
  last_hid_state_joint: any = None
  cls_embed_joint: any = None
  tokenized_joint: any = None
  tensorized_joint: any = None
  embed_joint: any = None
  last_hid_state_joint: any = None
  cls_embed_joint: any = None
  token_type_ids: any = None


  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened


  def word_search(self, words_remove_tok_ids):
    sent1_has_word = False
    #sent2_has_word = False
    #10/29/25 update, adding it infrastructure for subtokens
    def contains_sequence(tokens, sequence):
      for seq in sequence:
        n = len(seq)
        for i in range(len(tokens) - n + 1):
           if tokens[i:i+n] == seq:
            return True
      return False

    sent1_has_word = contains_sequence(self.flatten_tok_s1, words_remove_tok_ids)
    #sent2_has_word = contains_sequence(self.flatten_tok_s2, words_remove_tok_ids)


    '''
    removal_set = set(words_remove_tok_ids)
    for token in self.flatten_tok_s1:
      if token in removal_set:
        sent1_has_word = True

    for token in self.flatten_tok_s2:
      if token in removal_set:
        sent2_has_word = True
    '''

    return sent1_has_word



  def copy_to_desword_pair(self):
    copied = deepcopy(self)

    return Desword_Pairs( row_num = copied.row_num,
                         sentence1_des= copied.sentence1,
                         sentence2_des = copied.sentence2,
                         gold_label = copied.gold_label,
                         tokenized_s1 = copied.tokenized_s1,
                         tokenized_s2 = copied.tokenized_s2,
                         flatten_tok_s1 = copied.flatten_tok_s1,
                         flatten_tok_s2 = copied.flatten_tok_s2,
                         pad_flat_tok_s1 = copied.pad_flat_tok_s1,
                         pad_flat_tok_s2 = copied.pad_flat_tok_s2,
                         tensorized_s1 = copied.tensorized_s1,
                         tensorized_s2 = copied.tensorized_s2,
                         pad_tensorized_s1 = copied.pad_tensorized_s1,
                         pad_tensorized_s2 = copied.pad_tensorized_s2,
                         embed_s1 = copied.embed_s1,
                         embed_s2 = copied.embed_s2,
                         last_hid_state_s1 = copied.last_hid_state_s1,
                         last_hid_state_s2 = copied.last_hid_state_s2,
                         cls_embed_1 = copied.cls_embed_1,
                         cls_embed_2 = copied.cls_embed_2,
                         mask_s1 = copied.mask_s1,
                         mask_s2 = copied.mask_s2,
                         tokenized_joint= copied.tokenized_joint,
                         tensorized_joint= copied.tensorized_joint,
                         embed_joint= copied.embed_joint,
                         last_hid_state_joint= copied.last_hid_state_joint,
                         cls_embed_joint= copied.cls_embed_joint,
                         token_type_ids = copied.token_type_ids)

#gonna have a desword pairs that stores the sentence 1's with preps and the sentence 2 that matches to them
#basically the P --> CS2 and variations of
#the another that has the sentence 2's and the sentence 1 that matches to them
#basically the CS1 --> H and variations of
#the removal of preps (or other words) shall take place as an external functions, and the variations of the pairs
#shall be stored as such in the sentence1_des and sentence2_des of appropriately labeled arrays of objects



def prep_data():
    print("prep data")

    #name of the multinli jsonl file
    file_name = "multinli_1.0_dev_matched.jsonl"

    path = "/content/drive/MyDrive/Colab Notebooks/DataforGetCLSofJust2sets"

    #11/2/2025 additions (just to test if it can do "in" and then "inside") it can -- commented code was deleted but yea it can do subtokens just fine

    entries = []
    #12/14/2025 --- Trying to mount google drive to see if it'll work this way. hasn't been ran yet.
    with open(path + '/' + file_name, "r", encoding="utf-8") as file:
      for index, line in enumerate(file):
        data_line = json.loads(line)
        entry = MultiNLI_entry(
            row_num = index,
            sentence1 = data_line.get("sentence1", ""),
            sentence2 = data_line.get("sentence2", ""),
            gold_label = data_line.get("gold_label", ""),
        )

        entries.append(entry)



    '''
    with open(file_name, "r", encoding="utf-8") as file:
      for index, line in enumerate(file):
        data_line = json.loads(line)
        entry = MultiNLI_entry(
            row_num = index,
            sentence1 = data_line.get("sentence1", ""),
            sentence2 = data_line.get("sentence2", ""),
            gold_label = data_line.get("gold_label", ""),
        )

        entries.append(entry)
    '''

    if len(entries) < 10000:
      raise ValueError(f"Partial Read! Only found {len(entries)} lines!")


    return entries

#I could have made this a method
def tokenize_data(entries, tokenizer):
  print("tokenize data")

  for entry in entries:
    entry.tokenized_s1 = tokenizer.encode(entry.sentence1, return_tensors = "tf")
    #print(entry.tokenized_s1)
    entry.tokenized_s2 = tokenizer.encode(entry.sentence2, return_tensors = "tf")
    #print(entry.tokenized_s2)

def flatten_data(entries, tokenizer):
  print("calls class MultiNLI method to flatten data")

  for entry in entries:
    entry.flatten_tf_to_list()
    #print(type(entry.flatten_tok_s1))
    #print(type(entry.flatten_tok_s2))


def desired_words_to_remove(tokenizer):
  #for now this is hard_coded in, later I want this to be a text file that you can insert for custom words
  print("desired words to be removed")

  '''

  words_to_remove = ["on top", "in front", "next to",
    "in", "out", "over", "under", "above", "below", "inside",
    "outside", "around", "behind", "on", "near", "through",
    "throughout", "beneath", "into", "beside", "off", "between",
    "next", "upon", "from"]
  '''

  '''
  words_to_remove = ["in"]  #12/16/2025; doing to one just to test!
  '''

  #as of 12/18/2025, I realize that multiword prepositions must go first. Otherwise, they get clipped.

  words_to_remove = ["on top","in", "out", "over", "under",
                     "above", "below", "inside", "outside",
                     "around", "behind", "on" , "through"]



  '''
  #now we are testing this 12/16/2025 8:04pm
  words_to_remove = ["in", "out", "over", "under",
                     "above", "below", "inside", "outside",
                     "around", "behind", "on" , "on top", "through"]
  '''


  '''

  words_to_remove = ["in", "out", "over", "under",
                     "above", "below", "inside", "outside",
                     "around", "behind", "on" , "on top", "in front",
                     "near", "through", "throughout", "next to",
                     "beneath", "into", "beside", "off", "between",
                     "next", "upon", "from"]
  '''


  #11/2/2025 these all work properly, so the multitoken/subtokenization removal is working as intended.
  #words_to_remove = ["inside", "in"]  #10/29/2025 adding onto this!  (41 pcs2, 39 p_cs2) sentence 161 has the word "inside" and "in" in it
  #words_to_remove = ["in", "inside"]   #11/2/2025  (41 pcs2, 39 p_cs2) okay the shapes are right.
  #words_to_remove = ["in"] #(41 pcs2, 40 p_cs2) okay the shapes are right here too.
  #words_to_remove = ["inside"]  #(41 pcs2, 40 p_cs2) okay also good here, but I still need to print it all out to make sure it is removing the right ones
  #words_to_remove = ["oioewnoinaonen"]  #and this creates an error, which is what I was hoping for.



  #10/29/25 changing this to do subtokenization
  #this is actually whole sequences of ids now
  words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False) for word in words_to_remove]


  #words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False)[0] for word in words_to_remove]




  print("Token Ids of words to remove: ", words_remove_tok_ids)
  return words_remove_tok_ids



  #finish this later

  #remove_words_token_ids = {key: tokenizer.encode(key, add_special_tokens = False)}

def noting_preps():
  print("placeholder here")


def find_sentences_with_only_desired_words_to_remove(words_remove_tok_ids, all_nli_entries):
  print("this should find only the sentences with the desired words to remove and store them in an new array of MultiNLI classes")
  #entries but only the entries that contain the desired words to be removed
  entries_deswords_s1 = [] #where s1 has the entries we want and s2 is just along for ride
  #entries_deswords_s2 = [] #where s2 has the entries we want and s1 is just along for ride

  counter_s1 = 0
  #counter_s2 = 0

  #marks true or false for any entry in all the nli data if there is a sentence with a preposition
  for entry in all_nli_entries:
    sent1_has_word = entry.word_search(words_remove_tok_ids)
    #print(sent1_has_word, sent2_has_word)


    #for the
    if sent1_has_word: #and not sent2_has_word:
      #print("place holder")
      new_desword_pair = entry.copy_to_desword_pair() #is this how I do it? #8/15 update, I added the parenthesis and now it works
      entries_deswords_s1.append(new_desword_pair)
      #deep copy any sent1 with words to desword pair
      counter_s1 += 1

  '''
    if sent2_has_word: #and not sent1_has_word:
      #print("place holder")
      new_desword_pair = entry.copy_to_desword_pair()
      entries_deswords_s2.append(new_desword_pair)
      #deep copy any sent2 with words to desword pair
      counter_s2 += 1
  '''


  #as a test
  print(" p --> cs2")
  print(entries_deswords_s1[0])
  #print(" cs1 --> h")
  #print(entries_deswords_s2[0])     ---- 11/2/2025 this was commended out

  print("counter_s1: ",  counter_s1 )
  #print("counter_s2: ",  counter_s2)


  return entries_deswords_s1, counter_s1


def remove_desired_words_from_sentences(pcs2, words_remove_tok_ids, tokenizer):
  print("use the tokenizer to remove the tokens that correspond to the tokens of the words to remove")

  p_cs2 = []


  '''
  pcs2_ = []

  p_cs2_ = []
  '''

  '''

  cs1_h = []
  cs1h_ = []
  cs1_h_ = []

  '''



  for entry in pcs2:
    p_mod = entry.word_search_and_remove(words_remove_tok_ids)
    p_cs2.append(p_mod)
    #pcs2_.append(cs2_mod)
    #p_cs2_.append(both_mod)

  print("______________________________________")
  '''

  for entry in cs1h:
    cs1_mod, h_mod, both_mod = entry.word_search_and_remove(words_remove_tok_ids)
    cs1_h.append(cs1_mod)
    cs1h_.append(h_mod)
    cs1_h_.append(both_mod)
  '''



  return p_cs2


def unflatten_tokens_back_to_tensors(data_set):
  for entry in data_set:
    entry.convert_back_to_tensors()

def pad_helper(data_set):

  max_seq_len_ten_s1, max_seq_len_ten_s2 = max_seq_len_finder(data_set)

  for entry in data_set:
    entry.pad_tensors(max_seq_len_ten_s1, max_seq_len_ten_s2) #hope this works 8/24/2025

def pad_helper_joint(data_set):
  print("placeholder")


def max_seq_len_finder(data_set):
  print("placeholder")

  all_seq_lens_in_data_set = max_seq_len_getter(data_set)

  max_seq_len_in_data_set_s1 = max(entry[3] for entry in all_seq_lens_in_data_set)
  max_seq_len_in_data_set_s2 = max(entry[4] for entry in  all_seq_lens_in_data_set)

  return max_seq_len_in_data_set_s1, max_seq_len_in_data_set_s2

def max_seq_len_getter(data_set):
  all_seq_lens_in_data_set = []

  for entry in data_set:
    all_seq_lens_in_data_set.append(shape_getter(entry))

  return all_seq_lens_in_data_set


def shape_getter(entry):
  return  ( entry.row_num,                    #0
            entry.get_shape_tok_s1()[1],         #1
            entry.get_shape_tok_s2()[1],         #2
            entry.get_shape_tensorized_s1()[1],  #3
            entry.get_shape_tensorized_s2()[1])  #4   #all the shapes are 2d, I only care about the second dimension

def shape_getter_pad_ten(entry):

  return (entry.row_num,
          entry.get_shape_pad_ten_s1()[1],
          entry.get_shape_pad_ten_s2()[1])


def shape_checker_pad_ten(data_set):
  data_set_storage = []
  max_seq_len_in_data_set_s1, max_seq_len_in_data_set_s2 = max_seq_len_finder(data_set)

  for entry in data_set:
    data_set_storage.append(shape_getter_pad_ten(entry))

  #this gets the minimmum sequence lenght (2d dimension for the padded)
  min_seq_len_in_data_set_s1 = min(entry[1] for entry in data_set_storage)
  min_seq_len_in_data_set_s2 = min(entry[2] for entry in data_set_storage)

  #since this was padded, the min_seq_length should be the same as the max_seq_length

  if max_seq_len_in_data_set_s1 == min_seq_len_in_data_set_s1:
    print("the padding worked")
  else:
    print("something fishy here")
    print(max_seq_len_in_data_set_s1, min_seq_len_in_data_set_s1)


  if max_seq_len_in_data_set_s2 == min_seq_len_in_data_set_s2:
    print("the padding worked")
  else:
    print("something fishy here")
    print(max_seq_len_in_data_set_s2, min_seq_len_in_data_set_s2)

  '''

  for entry in data_set_storage:
    print(f"data_set {data_set}, row_num: {entry[0]}, pad_tok_s1: {entry[1]}, pad_tok_s2: {entry[2]}")

  '''


def get_cls_embeds(data_set):

  for entry in data_set:
    get_last_hid_state(entry)
    entry.cls_embed_from_last_hid_state()
    #print(entry.get_cls_embeds_rownum())


def get_last_hid_state(entry):
  get_embeds(entry)
  entry.last_hid_state_from_embed()
  return


def get_embeds(entry):
  entry.embed_the_padded_tensors()
  return

def flatten_og_prior_to_copy(all_nli_entries):
  for entry in all_nli_entries:
    entry.flatten_tf_to_list()

def copy_og_onto_desword_class(all_nli_entries):

  og_in_desword = []

  for entry in all_nli_entries:
    og_pair = entry.copy_to_desword_pair()
    og_in_desword.append(og_pair)




  return og_in_desword, len(og_in_desword)


def get_shape_of_last_hid_state(data_set):
  for entry in data_set:
    print(entry.get_last_hid_state_shape_s1())
    print(entry.get_last_hid_state_shape_s2())

def pickle_file(data_set, file_name):
  folder_path = '/content/drive/MyDrive/Colab Notebooks/DatafromCLSforImportConcateEval'
  os.makedirs(folder_path, exist_ok=True) #makes the file directory if it don't exist
  file_path = os.path.join(folder_path, file_name + ".pkl")


  with open(file_path, 'wb') as db_file:
    pickle.dump(data_set, db_file)

  '''
  db_file = open(f'pickled {data_set}', 'wb')
  pickle.dump(data_set, db_file)
  db_file.close()
  '''

def make_attention_mask(data_set):
  print("trying to make a mask")
  mask_s1 = []
  mask_s2 = []
  for entry in data_set:
    entry_mask_s1, entry_mask_s2 = entry.attention_mask()
    mask_s1.append(entry_mask_s1)
    mask_s2.append(entry_mask_s2)

  return mask_s1, mask_s2

def joint_maker_helper(data_set):
  for entry in data_set:
    entry.joint_maker()

def joint_embedder_helper(data_set):
  print("a")
  #https://www.reddit.com/r/deeplearning/comments/1da8p75/my_experience_with_bert_on_mnli/
  for entry in data_set:
    entry.embed_joint_tensors()

def joint_last_hid_state_helper(data_set):
  for entry in data_set:
    entry.last_hid_state_from_embed_joint()

def joint_cls_embed_from_last_hid_state(data_set):
  for entry in data_set:
    entry.cls_embed_from_last_hid_state_joint()





def main():
  print("start of program")
  #running that following line actually breaks code.
  #tf.keras.backend.clear_session() #this was added 12/17/2025 at the behest of GPT advice (clears out junk data that may be left over from previous runs)
  all_nli_entries = prep_data()
  print(all_nli_entries)

  #tokenize_data function returns a tensorflow tensor
  tokenize_data(all_nli_entries, tokenizer)
  #remember that all_nli_entries is all 10000 sentences, if we are gonna search and rip prepositions
  #we need have two functions that search those, put them into another class MultiNLI, then another function to
  #search and destroy the preps. Has to happen between tokenize and tensorize steps
  #the cls embeds for all the tensorized data could be used as training data over in the other file?
  flatten_data(all_nli_entries, tokenizer)
  words_remove_tok_ids = desired_words_to_remove(tokenizer)

  print(all_nli_entries[0])
  #at this point, pcs2 and cs1h should still be flattened, same as all_nli_entries 8/23/2025 note
  #a later function is needed to unflatten/convert them back to tensorsflow tensors
  #actually wrong 8/23 note, but later, they are flattened inside the object?
  pcs2, word_counter_s1 = find_sentences_with_only_desired_words_to_remove(words_remove_tok_ids, all_nli_entries)
  #flatten_og_prior_to_copy(all_nli_entries) #important this step happens before the copy
  #og_set, len_og_set = copy_og_onto_desword_class(all_nli_entries)
  #print(len_og_set)
  #print(og_set[0].flatten_tok_s1)
  #print(og_set[0].flatten_tok_s2)
  del all_nli_entries #at behest of Google Colabs 12/17/2025, we get rid of all_nli_entries since we no longer use it
  gc.collect() #then try to free up that memory.


  #very important make sure to uncomment (9/3/2025 -- 2:03pm)
  #commented out for now to work on OG


  print(pcs2[0].flatten_tok_s1)
  print(pcs2[0].flatten_tok_s2)



  #word_counter_s1 and word_counter_s2 should match the counter coming out the removed
  #preps method named word_search_and_remove of the Desired_Pairs class
  #if they don't something went wrong

  p_cs2 = remove_desired_words_from_sentences(pcs2, words_remove_tok_ids, tokenizer)

  print("look here aswell2")

  print(tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(pcs2[0].flatten_tok_s1)))
  print(tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(p_cs2[0].flatten_tok_s1)))





  #these tokens are not truly unflattened!
  #https://www.tensorflow.org/api_docs/python/tf/reshape you can reshape a tensors with sequence length
  #all my tensors are (1, Xth dimension of sequence length)
  #tf.reshape(tf.convert_to_tensor(dataset, dtype= tf.int32), (1, sequence_length))
  unflatten_tokens_back_to_tensors(pcs2)
  unflatten_tokens_back_to_tensors(p_cs2)


  print(pcs2[0].tensorized_s1)
  print(pcs2[0].tensorized_s2)

  joint_maker_helper(pcs2)

  print(pcs2[0].tensorized_s2)

  print(pcs2[0].tensorized_joint)

  print("\n________________________\n")

  print(p_cs2[0].tensorized_s1)
  print(p_cs2[0].tensorized_s2)


  joint_maker_helper(p_cs2)

  print(p_cs2[0].tensorized_s2)
  print(p_cs2[0].tensorized_joint)




  #print(1/0)  #<______________ this is here to intentionally stop my program because colabs is an IDE that doesn't have stops on lines

  joint_embedder_helper(pcs2)
  print(0)
  joint_embedder_helper(p_cs2)
  print(1)

  joint_last_hid_state_helper(pcs2)
  print(2)
  joint_last_hid_state_helper(p_cs2)
  print(3)

  joint_cls_embed_from_last_hid_state(pcs2)
  print(4)
  joint_cls_embed_from_last_hid_state(p_cs2)
  print(5)

  '''








  #do the joints here



  #unflatten_tokens_back_to_tensors(og_set)   # 9/5/2025 update, unflattens og set


  print("hey look here")
  print(pcs2[0].tensorized_s1.shape)
  print(pcs2[0].tokenized_s1.shape)


  #print(og_set[0].tensorized_s1.shape)
  #print(og_set[0].tokenized_s1.shape)




  print("pcs2: (max_seq_len_ten_s1, max_seq_len_ten_s2): ", max_seq_len_finder(pcs2))
  print("p_cs2: (max_seq_len_ten_s1, max_seq_len_ten_s2): ", max_seq_len_finder(p_cs2))



  #print("og_set: (max_seq_len_ten_s1, max_seq_len_ten_s2): ", max_seq_len_finder(og_set))




  #I need to find what the highest 2nd dimensional value of the shape of the tensorized_s1 and tensorized_s2 is
  #so that I can use it to pad everything to a uniform length
  #so I'll need to store (using the shape getter (it returns a tuple)) all the values into a an array that
  #hold the second value and the rownum in a tuple.
  #then use a search algorithm
  #how does python divide a tuple if I return three values


  pad_helper(pcs2)
  pad_helper(p_cs2)


  #pad_helper(og_set)


  make_attention_mask(pcs2)
  make_attention_mask(p_cs2)


  shape_checker_pad_ten(pcs2)
  shape_checker_pad_ten(p_cs2)


  #shape_checker_pad_ten(og_set)  #added on 9/5/2025 at 9:47pm




  get_cls_embeds(pcs2)
  get_cls_embeds(p_cs2)

  #stole this from google gemini
  # Check pcs2 (Desword_Pairs)
  if len(pcs2) > 0:
      assert not tf.reduce_all(
          tf.equal(pcs2[0].cls_embed_1, pcs2[0].cls_embed_2)
      ), "CRITICAL ERROR: S1 and S2 embeddings are identical in pcs2! Check last_hid_state_from_embed."

  # Check p_cs2 (Desword_Pairs)
  if len(p_cs2) > 0:
      assert not tf.reduce_all(
          tf.equal(p_cs2[0].cls_embed_1, p_cs2[0].cls_embed_2)
      ), "CRITICAL ERROR: S1 and S2 embeddings are identical in p_cs2! Check last_hid_state_from_embed."

  print("Sanity check passed: S1 and S2 are distinct.")
  # --- SANITY CHECK END ---

  #checks to make sure no partial data in pcs2 or p_cs2

  orphans = 0
  for i, entry in enumerate(pcs2):
      # We check cls_embed_1 because it's the very last thing you create.
      # If this is None, the loop died early.
      if entry.cls_embed_1 is None:
          orphans += 1

  if orphans > 0:
    # This stops the code so you don't pickle bad data
    raise RuntimeError(f" DATA CORRUPTION: Found {orphans} entries in pcs2 that are missing embeddings! The run likely timed out.")
  else:
      print(" Integrity Check: All entries in pcs2 have embeddings.")

  orphans_again = 0
  for i, entry in enumerate(p_cs2):
      # We check cls_embed_1 because it's the very last thing you create.
      # If this is None, the loop died early.
      if entry.cls_embed_1 is None:
          orphans += 1

  if orphans_again > 0:
    # This stops the code so you don't pickle bad data
    raise RuntimeError(f" DATA CORRUPTION: Found {orphans} entries in p_cs2 that are missing embeddings! The run likely timed out.")
  else:
      print(" Integrity Check: All entries in p_cs2 have embeddings.")











  #get_cls_embeds(og_set) #added on 9/5/2025




  print(len(pcs2))
  #get_shape_of_last_hid_state(pcs2)

  print( " _______________________________ ")

  print(len(p_cs2))
  #get_shape_of_last_hid_state(p_cs2)

  # Print shapes for first 5 entries to spot check
  for i in range(5):
      if i < len(pcs2):
          print(f"Entry {i} S1 Shape: {pcs2[i].last_hid_state_s1.shape}")
  '''


  pickle_file(pcs2, "pcs2_13versionJointed")
  pickle_file(p_cs2, "p_cs2_13versionJointed")
  #pickle_file(og_set, "og_set")






  #I need to find what the highest 2nd dimensional value of the shape of the tensorized_s1 and tensorized_s2 is
  #so that I can use it to pad everything to a uniform length
  #so I'll need to store (using the shape getter (it returns a tuple)) all the values into a an array that
  #hold the second value and the rownum in a tuple.
  #then use a search algorithm
  #how does python divide a tuple if I return three values



  #check if Tensorflow is finding the GPU's


  print(tf.config.list_physical_devices('GPU'))





#____________________________________________________________________
#PICKLING THE FILES






  #pad after finding and removing

  #retokenize








if __name__ == "__main__":
  main()