# -*- coding: utf-8 -*-
"""GettingSampleSentencesForPresentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10-8oM7_gd6fl0_O5WR0JcuKk7bUYw6lj
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install fpdf

'''
getting modified data
'''


import copy  #we are gonna need this bad boy right here
from datasets import Dataset
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
import torch
from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)
from torch.utils.data import DataLoader
from tqdm.auto import tqdm  #add progress bars
import os
import random

def data_prepare():
  print("prepare data")
  #name of the multinli jsonl file
  file_name = "multinli_1.0_dev_matched.jsonl"
  path = "/content/drive/MyDrive/Colab Notebooks/DataGettingSampleSentencesForPresentation"
  #https://pandas.pydata.org/docs/reference/api/pandas.read_json.html  I can read this shit line by line with pandas

  entries_full = pd.read_json(path + '/' + file_name, lines = True, encoding = "utf-8")
  cols = entries_full.columns
  print(f"name of variables: {cols}")
  variables_needed = ['gold_label', 'sentence1', 'sentence2']

  #https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.copy.html

  entries = entries_full[variables_needed].copy(deep=True)
  return entries


def tokenize(entries):
  print("tokenize")
  #https://stackoverflow.com/questions/73154119/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object
  dataset = Dataset.from_pandas(entries)
  #https://huggingface.co/docs/datasets/v1.8.0/processing.html
  tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

  #sentence1 = premise
  #sentence2 = hypothesis

  # This just sentence 1.
  def tokenize(batch):
      return tokenizer(
          batch["sentence1"],
          truncation=True,
          padding=False,
          max_length=128
      )

  #https://huggingface.co/docs/datasets/en/about_map_batch
  dataset = dataset.map(tokenize, batched=True)

  # set pytorch format:
  #columns = ["input_ids", "attention_mask", "token_type_ids", "label"]
  #dataset.set_format(type="torch")  #remove the columns
  #print("pytorch format made")

  print("done with tokenization")
  print(dataset["sentence1"])
  print(dataset["input_ids"])
  return dataset, tokenizer


def deswords_tok(tokenizer):
  words_to_remove = ["on top", "in front", "next to",
                      "in", "out", "over", "under", "above", "below", "inside",
                      "outside", "around", "behind", "on", "near", "through",
                      "throughout", "beneath", "into", "beside", "off", "between",
                      "next", "upon", "from"]

  words_remove_tok_ids = [tokenizer.encode(word, add_special_tokens = False) for word in words_to_remove]
  print("Token Ids of words to remove: ", words_remove_tok_ids)
  return words_remove_tok_ids



def find(entries_tok_s1, to_remove):
  #the code here is halfway between psuedocode and real code it won't run yet.


  def contains_sequence(main_sequence, sub_sequence):
        n = len(sub_sequence)
        for i in range(len(main_sequence) - n + 1):
            if main_sequence[i:i+n] == sub_sequence:
                return True
        return False


  def filter_logic(data_set):
    input_ids = data_set['input_ids']
    for bad_word in to_remove:
      if contains_sequence(input_ids, bad_word):
        return True #keep row
    return False #no keep


  #https://huggingface.co/docs/datasets/en/process  #give it some logic and it'll filter rows based on that logic (whatever function you feed it)

  to_be_modified = entries_tok_s1.filter(filter_logic)

  print(len(entries_tok_s1))
  print(len(to_be_modified))

  return to_be_modified


def find_remove(entries_tok_s1, to_remove, tokenizer):

  #this only filters one entry in the full data set. So I gotta loop through this damn thing for each entry in the dingdang data set
    def filter_subseq(to_modify, to_remove):
      modified = [] #wwhere I save the shit
      n = len(to_remove) #this is not needed
      i = 0 #starts off at start at first token in our input string of tokens
      while i < len(to_modify):
        matched = False #reset at every removal
        for token in to_remove: #checks through every banned word in our list of word tokens to remove
          m = len(token) #sets the lengt to check to the end of the length of whatever current token string we are looking at
          if to_modify[i:i+m] == token: #if there is a matching token anywhere that looks like the token we want to remove #this gave a slice error because I tried to put an entire data set in here and not just a singular column so I ahve to change it up and add some filter logic with some batches
            matched = True #change the flag
            i += m #skip it matching token
            break #break the foor loop, but continue the while loop such that we keep checking the rest of the token string
        if not matched: #any token that is not on the banned word list enters the modified list, so banned words are excluded
          modified.append(to_modify[i])
          i += 1  #moves onto next token in string of tokens
      return modified

    #adding this filter logic function after spitballing with GeminiAI as it gave me a faster method to converting the filtered token strings back to words than what I had planned
    def filter_logic(batch):
      new_ids = filter_subseq(batch['input_ids'], to_remove)
      new_sentence = tokenizer.decode(new_ids, skip_special_tokens = True)  #<-- I am not sure if I want to skip these special tokens, unless they are recreated later in cell 2
      return {
          "input_ids" : new_ids, #I will end up deleting this column. But i'll save it for now just in case
          "sentence1" : new_sentence   #replaces the old sentence1 with the new sentence 1 that should be lacking prepositions
      }


    modified_dataset = entries_tok_s1.map(filter_logic)


    return modified_dataset


def drop_cols_i_hate(dataset):
  #https://huggingface.co/docs/datasets/v1.4.0/processing.html#removing-one-or-several-columns-remove-columns
  #there is a disgusting hair in my keyboard trying to slide under my spacebar
  dataset.remove_columns(["input_ids", "attention_mask", "token_type_ids"])
  return dataset



#silly me I forgot this very important step!
def make_copy_of_unmod(data_set):
  print("haodi")
  corresponding_unmodified_data = copy.deepcopy(data_set)
  return corresponding_unmodified_data

#yes, I took this last part from AI. I have a week until presentation time,
'''
def extract_presentation_examples(unmod_ds, mod_ds, num_examples=10):
    print("\n--- Examples for Presentation ---")

    # Convert to pandas for easier row-by-row viewing
    df_unmod = unmod_ds.to_pandas()
    df_mod = mod_ds.to_pandas()

    # We want to see the change, so let's look at the first few rows
    for i in range(min(num_examples, len(df_unmod))):
        print(f"Example {i+1}:")
        print(f"  [Label]:      {df_unmod.iloc[i]['gold_label']}")
        print(f"  [Original S1]: {df_unmod.iloc[i]['sentence1']}")
        print(f"  [Modified S1]: {df_mod.iloc[i]['sentence1']}")
        print(f"  [Hypothesis]:  {df_unmod.iloc[i]['sentence2']}")
        print("-" * 30)

    # Optional: Save a small CSV of just these pairs to copy-paste easily
    comparison_df = pd.DataFrame({
        'Label': df_unmod['gold_label'],
        'Original_S1': df_unmod['sentence1'],
        'Modified_S1': df_mod['sentence1'],
        'Hypothesis': df_unmod['sentence2']
    })

    # Save a small sample to your drive
    sample_path = "/content/drive/MyDrive/Colab Notebooks/DataGettingSampleSentencesForPresentation/presentation_samples.csv"
    comparison_df.head(50).to_csv(sample_path, index=False)
    print(f"Comparison samples saved to {sample_path}")
'''
'''
def extract_random_presentation_samples(unmod_ds, mod_ds, num_examples=10):
    print(f"\n--- Random Sample of {num_examples} Pairs for Slides ---")

    # Convert to pandas to make indexing easier
    df_unmod = unmod_ds.to_pandas()
    df_mod = mod_ds.to_pandas()

    # Get total available rows
    total_rows = len(df_unmod)

    # Ensure we don't try to sample more rows than we actually have
    sample_size = min(num_examples, total_rows)

    # Generate random indices
    random_indices = random.sample(range(total_rows), sample_size)

    for idx in random_indices:
        label = df_unmod.iloc[idx]['gold_label']
        orig_s1 = df_unmod.iloc[idx]['sentence1']
        mod_s1 = df_mod.iloc[idx]['sentence1']
        hypo = df_unmod.iloc[idx]['sentence2']

        print(f"Index: {idx} | Label: {label.upper()}")
        print(f"  [Original]: {orig_s1}")
        print(f"  [Modified]: {mod_s1}")
        print(f"  [Hypothesis]: {hypo}")
        print("-" * 50)

'''

def extract_random_presentation_samples(unmod_ds, mod_ds, num_examples=50):
    print(f"\n--- Random Sample of {num_examples} Pairs for Slides ---")

    # Convert to pandas
    df_unmod = unmod_ds.to_pandas()
    df_mod = mod_ds.to_pandas()

    total_rows = len(df_unmod)
    sample_size = min(num_examples, total_rows)

    # Generate random indices
    random_indices = random.sample(range(total_rows), sample_size)

    # List to store data for CSV
    csv_data = []

    for idx in random_indices:
        label = df_unmod.iloc[idx]['gold_label']
        orig_s1 = df_unmod.iloc[idx]['sentence1']
        mod_s1 = df_mod.iloc[idx]['sentence1']
        hypo = df_unmod.iloc[idx]['sentence2']

        # Print to console for quick viewing
        print(f"Original Index: {idx} | Label: {label.upper()}")
        print(f"  [Original]: {orig_s1}")
        print(f"  [Modified]: {mod_s1}")
        print(f"  [Hypothesis]: {hypo}")
        print("-" * 50)

        # Add to list with explicit index
        csv_data.append({
            'original_index': idx,
            'gold_label': label,
            'sentence1_original': orig_s1,
            'sentence1_modified': mod_s1,
            'sentence2_hypothesis': hypo
        })

    # Save to CSV
    sample_df = pd.DataFrame(csv_data)
    folder_path = "/content/drive/MyDrive/Colab Notebooks/DataGettingSampleSentencesForPresentation"
    os.makedirs(folder_path, exist_ok=True)
    csv_path = os.path.join(folder_path, "presentation_samples_with_index2.csv")

    sample_df.to_csv(csv_path, index=False)
    print(f"Successfully saved {sample_size} examples to {csv_path}")

def find_specific_sentence_match(unmod_ds, mod_ds):
    # Convert to pandas
    df_unmod = unmod_ds.to_pandas()
    df_mod = mod_ds.to_pandas()

    search_target = "then he gave in"

    # Filter for exact matches (ignoring case/whitespace)
    #matches = df_unmod[df_unmod['sentence1'].str.lower().str.strip() == search_target.lower()]
    matches = df_unmod[df_unmod['sentence1'].str.contains("then he gave in", case=False, na=False)]

    if matches.empty:
        print(f"Bummer! No matches found for '{search_target}'.")
        print("Tip: Check if the original sentence has a period at the end!")
        return

    print(f"Found {len(matches)} exact match(es) for '{search_target}':\n")

    for idx in matches.index:
        print(f"Index: {idx} | Label: {df_unmod.loc[idx, 'gold_label'].upper()}")
        print(f"  [Original S1]: {df_unmod.loc[idx, 'sentence1']}")
        print(f"  [Modified S1]: {df_mod.loc[idx, 'sentence1']}")
        print(f"  [Sentence 2]:  {df_unmod.loc[idx, 'sentence2']}")
        print("-" * 50)


def main():
  print("main main")
  print("main")
  entries = data_prepare()
  #https://discuss.huggingface.co/t/from-pandas-dataframe-to-huggingface-dataset/9322
  #print(entries)
  #entries = filter_out_hyphen_labels(entries)
  #print(entries)
  #entries = gold_label_to_integers(entries)  <--- I actually don't want to get rid of hyphens or change labels to integers, since the next google colabs cell will do that.
  #print(entries)


  #entries_tok_s1 has the same data type as entries
  #convert sentence 1 to tokens
  entries_tok_s1, tokenizer = tokenize(entries)
  print(entries_tok_s1)
  print(type(entries_tok_s1))
  print(type(entries_tok_s1["input_ids"]))

  to_remove = deswords_tok(tokenizer)
  #identify sentence 1s with prepositions; save index number to later put sentence pairs + labels in their own data set
  #data types of to_be_modified is same as entries_tok_s1 (so it has all the columns, so data shouldn't get fucked up/missmapped)
  to_be_modified = find(entries_tok_s1, to_remove)
  #to_be_modified = we have a dataset of only the sentences with select words, but they have not been modified to remove them yet.
  corresponding_unmodified_set = make_copy_of_unmod(to_be_modified)

  #remove prepositions from that the sentence 1s that were confirmed to have prepositions
  #and deconverts sentence 1 back to regular sentence data
  #and puts the modified sentence 1 back into the running data set,
  #which means taking input_ids column, making changing it back to words,
  #shoving it into the sentence 1 column, and then delete the input_ids column to make space for it later,
  #data structure is still the same
  modified_s1 = find_remove(to_be_modified, to_remove, tokenizer)

  #the hugging face filter log

  #print(entries['sentence1'])
  #print(modified_s1["sentence1"])

  print(len(modified_s1)) #the hugging face filter logic prevents this from
  print(len(entries))

  len_mod = len(modified_s1)
  len_unmod = len(corresponding_unmodified_set)

  if len_mod != len_unmod:
    print("lenghts of data sets don't match, something is wrong")
    print(len_mod)
    print(len_unmod)
  else:
    print(len_mod)
    print(len_unmod)
    print("the lengths match")

  # and then delete the input_ids column to make space for it later
  modified_data = drop_cols_i_hate(modified_s1)
  unmodified_data = drop_cols_i_hate(corresponding_unmodified_set)


  #save_data(modified_data, "modified_multinli_25preps")
  #save_data(unmodified_data, "unmodified_multinli_25preps")
  find_specific_sentence_match(unmodified_data, modified_data)

  #extract_random_presentation_samples(unmodified_data, modified_data, num_examples=50)

  #save it into google drive folder such that it can be called in other Google Colab Cell



if __name__ == "__main__":
  main()