# -*- coding: utf-8 -*-
"""ImportPickleConcateEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vRgWf5VpWdEIvCpAKG-SmOXZnuiYr_O7
"""

from google.colab import drive
drive.mount('/content/drive')

# -*- coding: utf-8 -*-
"""
Kyle Urban
University of Central Arkansas
Capstone File #1


"""
from dataclasses import dataclass
from copy import deepcopy
import pickle
from datetime import datetime
import math
import torch  #May 31st, 2025 update, added in PyTorch cuz https://tenor.com/search/spongebob-i-need-it-gifs
import json
import os
import numpy as np #very important to the sanity check in part 2
import pandas as pd
#print(pd.__version__)
import tensorflow as tf
#print(tf.__version__)
from transformers import TFBertModel
from transformers import BertTokenizer

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_model = TFBertModel.from_pretrained("bert-base-uncased", from_pt = True)  #Update as of 4/2/25 # 8/8 update, you hav eto use the from_pt = True now as Huggingface got an update


from transformers import BertConfig
bert_config = BertConfig.from_pretrained('bert-base-uncased')
from sklearn.linear_model import LogisticRegression as lg #Dr Stine recommended this classifier model in place of AutoModelforSequenceClassification
from sklearn.pipeline import Pipeline as pipe #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
from sklearn.preprocessing import StandardScaler #CHATGPT recommended this when I asked about other useful sklearn tools that would be useful for LogisticRegression
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score, cross_validate

from sklearn.preprocessing import LabelEncoder    #10/18/2025 Borrowed from ChatGPT (I have to make the gold labels numbers)
from sklearn.decomposition import PCA #12/27/2025 @10:19pm I shot a deer. Holy shit I have nw realized this basically just looks for eigenvectors and realigns the space based on them.
#from sklearn.metrics import confusion_matrix  #12/31/2025 @11am gonna import this too becuase why not?  @11:30a, I realize I don't need this for anything
#https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
#https://www.geeksforgeeks.org/machine-learning/implementing-pca-in-python-with-scikit-learn/
#these are useful pages
#https://www.geeksforgeeks.org/maths/covariance-matrix/


from numpy import mean
from numpy import absolute

#https://www.geeksforgeeks.org/dsa/random-forest-classifier-using-scikit-learn/    1/7/2026 NEW NEW NEW Direction
#https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

from sklearn.ensemble import RandomForestClassifier     #<---- we are gonna try something better than a logisitic regression model
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix #nvm I actually need this thing, also I didn't get my deerhide

#https://www.tensorflow.org/api_docs/python/tf/keras/losses/CosineSimilarity   <---- should I try throwing this in? 12/31/2025 @9:00pm
#where the hell would I even put it?
#I guess I'll make another class method on desword_pair just like I did with mean pool and concate.




#gonna use StratifiedKFold because I have no clue if the gold_labels are proportional to each other in the MultiNLI data


#move model onto GPU runtime to go faster (9/3/2025 update, ya' know ya boi got that google colabs pro)
''' #this is for pytorch only, tensorflow does this automatically
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model.to(device)
'''
#check if Tensorflow is finding the GPU's

print(tf.config.list_physical_devices('GPU'))



# Test tokenization
text = "Hello, TensorFlow!"
tokens = tokenizer.encode(text, return_tensors="tf")  # Use "tf" instead of "pt" for TensorFlow tensors


@dataclass
class Desword_Pairs:
  row_num: int
  sentence1_des: str
  sentence2_des: str
  gold_label: str
  tokenized_s1: any = None
  tokenized_s2: any = None
  flatten_tok_s1: any = None
  flatten_tok_s2: any = None
  pad_flat_tok_s1: any = None
  pad_flat_tok_s2: any = None
  tensorized_s1: any = None
  tensorized_s2: any = None
  pad_tensorized_s1: any = None
  pad_tensorized_s2: any = None
  embed_s1: any = None
  embed_s2: any = None
  last_hid_state_s1: any = None
  last_hid_state_s2: any = None
  cls_embed_1: any = None
  cls_embed_2: any = None
  mask_s1: any = None
  mask_s2: any = None
  tokenized_joint: any = None
  tensorized_joint: any = None
  embed_joint: any = None
  last_hid_state_joint: any = None
  cls_embed_joint: any = None
  token_type_ids: any = None


  def __init__(self, row_num ,sentence1_des ,sentence2_des ,  gold_label , tokenized_s1 ,   tokenized_s2 ,
               flatten_tok_s1 ,  flatten_tok_s2 ,  pad_flat_tok_s1 ,  pad_flat_tok_s2 , tensorized_s1, tensorized_s2,
               pad_tensorized_s1 ,  pad_tensorized_s2 ,  embed_s1 ,  embed_s2 , last_hid_state_s1 ,
               last_hid_state_s2 ,  cls_embed_1 , cls_embed_2, mask_s1, mask_s2, tokenized_joint,
               tensorized_joint,embed_joint, last_hid_state_joint, cls_embed_joint, token_type_ids):
    self.row_num = row_num
    self.sentence1_des = sentence1_des
    self.sentence2_des = sentence2_des
    self.gold_label = gold_label
    self.tokenized_s1 = tokenized_s1
    self.tokenized_s2 = tokenized_s2
    self.flatten_tok_s1 = flatten_tok_s1
    self.flatten_tok_s2 = flatten_tok_s2
    self.pad_flat_tok_s1 = pad_flat_tok_s1
    self.pad_flat_tok_s2  = pad_flat_tok_s2
    self.tensorized_s1 = tensorized_s1
    self.tensorized_s2 = tensorized_s2
    self.pad_tensorized_s1 = pad_tensorized_s1
    self.pad_tensorized_s2  = pad_tensorized_s2
    self.embed_s1 = embed_s1
    self.embed_s2 = embed_s2
    self.last_hid_state_s1 = last_hid_state_s1
    self.last_hid_state_s2 = last_hid_state_s2
    self.cls_embed_1 = cls_embed_1
    self.cls_embed_2 = cls_embed_2
    self.mask_s1 = mask_s1
    self.mask_s2 = mask_s2
    self.tokenized_joint= tokenized_joint
    self.tensorized_joint= tensorized_joint
    self.embed_joint= embed_joint
    self.last_hid_state_joint= last_hid_state_joint
    self.cls_embed_joint= cls_embed_joint
    self.token_type_ids = token_type_ids

#the Desword_pair object also needs it own flatten to list obbject
#may not actually need this object
  def flatten_tf_to_list(self):
    self.flatten_tok_s1 = self.tokenized_s1.numpy().flatten().tolist() #each line gets flattened
    self.flatten_tok_s2 = self.tokenized_s2.numpy().flatten().tolist() #each line gets flattened

  def convert_back_to_tensors(self):
    print("takes flattened tensors and makes them unflat")

    self.tensorized_s1 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s1, dtype=tf.int32), (1, len(self.flatten_tok_s1)))
    self.tensorized_s2 = tf.reshape(tf.convert_to_tensor(self.flatten_tok_s2, dtype=tf.int32), (1, len(self.flatten_tok_s2)))


  def pad_tensors(self, max_seq_len_ten_s1, max_seq_len_ten_s2):
    print("post pads all my tensors")



    self.pad_tensorized_s1 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s1, maxlen = max_seq_len_ten_s1, padding = "post")
    self.pad_tensorized_s2 = tf.keras.preprocessing.sequence.pad_sequences(self.tensorized_s2, maxlen = max_seq_len_ten_s2, padding = "post")
    #https://www.tensorflow.org/api_docs/python/tf/keras/utils/pad_sequences
    #rework the code here to get a maximum lenght atwhich the sequences can be padded 8/24/2025

    print("row number: ", self.row_num)
    print("pad_tensorized_s1: ", self.pad_tensorized_s1)
    print("pad_tensorized_s2: " , self.pad_tensorized_s2)


  def get_shape_tok_s1(self):
    return self.tokenized_s1.shape

  def get_shape_tok_s2(self):
    return self.tokenized_s2.shape

  def get_shape_tensorized_s1(self):
    return self.tensorized_s1.shape

  def get_shape_tensorized_s2(self):
    return self.tensorized_s2.shape

  def get_shape_pad_ten_s1(self):
    return self.pad_tensorized_s1.shape

  def get_shape_pad_ten_s2(self):
    return self.pad_tensorized_s2.shape

  def get_last_hid_state_shape_s1(self):
    return self.last_hid_state_s1.shape

  def get_last_hid_state_shape_s2(self):
    return self.last_hid_state_s2.shape


#necesary for the word_search and removal method
  def copy_deep(self):
    return deepcopy(self)

  def word_search_and_remove(self, words_remove_tok_ids):
    print(self.row_num)

    #gonna have to do this 3 times. Once for modifying the p/cs1, once for modifying the h/cs2, and then once for both modified
    #this should return 6 sets total I believe

    #in order to do this imma need to make deep copies of every self (every entry) 3 times inside here.

    #removing from the deep copied sets
    removal_set = set(words_remove_tok_ids)


    #https://realpython.com/python-enumerate/
    #https://www.w3schools.com/python/ref_list_pop.asp
    #https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
    #https://stackoverflow.com/questions/1207406/how-to-remove-items-from-a-list-while-iterating



    #Will the number of sentences that had a preposition removed be the same as the number of sentences that had a prepositions spotted?
    #go over your code logic with Dr Stine.


    #p' --> cs2 and cs1' --> h
    self_s1mod = self.copy_deep()
    self_s1mod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]


    #makes sense because when working cs1h, not all cs1s will have preps
    if (len(self_s1mod.flatten_tok_s1) == len(self.flatten_tok_s1)):
      print("len of s1  ")
      print(len(self.flatten_tok_s1))
      print("len of s1' ")
      print(len(self_s1mod.flatten_tok_s1))

    #p --> cs2' and cs1 --> h'
    self_s2mod = self.copy_deep()
    self_s2mod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]

    #makes sense because when working on pcs2, not all cs2s will have preps
    if (len(self_s2mod.flatten_tok_s2) == len(self.flatten_tok_s2)):
      print("len of s2  ")
      print(len(self.flatten_tok_s2))
      print("len of s2' ")
      print(len(self_s2mod.flatten_tok_s2))


    #p'--> cs2' and cs1' --> h'
    self_bothmod = self.copy_deep()
    self_bothmod.flatten_tok_s1 = [token for token in self.flatten_tok_s1 if token not in removal_set]
    self_bothmod.flatten_tok_s2 = [token for token in self.flatten_tok_s2 if token not in removal_set]







    return self_s1mod, self_s2mod, self_bothmod




  def embed_the_padded_tensors(self):

    self.embed_s1 = bert_model(self.pad_tensorized_s1)
    self.embed_s2 = bert_model(self.pad_tensorized_s2)


  def last_hid_state_from_embed(self):

    self.last_hid_state_s1 = self.embed_s1.last_hidden_state
    self.last_hid_state_s2 = self.embed_s2.last_hidden_state

  def cls_embed_from_last_hid_state(self):

    self.cls_embed_1 = self.last_hid_state_s1[:,0,:]
    self.cls_embed_2 = self.last_hid_state_s2[:,0,:]


  def get_cls_embeds_s1(self):
    return self.cls_embed_1

  def get_cls_embeds_s2(self):
    return self.cls_embed_2

  def get_cls_embeds_rownum(self):
    return self.row_num, self.cls_embed_1, self.cls_embed_2


  #https://arxiv.org/pdf/1705.02364
  #this article (page 3) explains why I need to use this
  #returns a tuple with the row_num, a concatenation of (cls1, cls2, element difference of cls1 and cls2, element wise product of cls1 and cls2) and the gold label
  def get_cls_embeds_rownum_concate_gold(self):
    #print(type(self.cls_embed_1), type(self.cls_embed_2)) #<--- these are tensorflow tensors
    cls1 = self.cls_embed_1.numpy()   #converts to numpy (cuz sk learns expects that )
    cls2 = self.cls_embed_2.numpy()
    #print("cls1 and cls2 shape: ")
    #print(cls1.shape)
    #print(cls2.shape)
    #axis = 1 is very important here because it keeps the dimensions of the matrices consistent (row-wise)
    #as everything is squished from R2 to R1  10/5/2025 110:4pm update
    combo = np.concatenate((cls1, cls2, np.abs(cls1 - cls2), cls1 * cls2), axis = 1)  #<--- most important line of code here!
    combo = combo[0] #<--- second most important line of code here flattens from R2 to R1 while preserving datat (gets rid of a batch dimesion of (1,n) to just (n,))
    return self.row_num, combo, self.gold_label

  def get_cls_embeds_rownum_concate_gold_joint(self):
    print("d")
    joint = self.cls_embed_joint.numpy()
    joint = joint[0] #yes okay this is important
    return self.row_num, joint, self.gold_label

  def get_cls_embeds_no_elemdiffpair(self):
    cls1 = self.cls_embed_1.numpy()   #converts to numpy (cuz sk learns expects that )
    cls2 = self.cls_embed_2.numpy()
    #print("cls1 and cls2 shape: ")
    #print(cls1.shape)
    #print(cls2.shape)
    combo = np.concatenate((cls1, cls2), axis = 1)   #should axis=1 done here since nothing
    #print(combo.shape)
    combo = combo[0]
    #print(combo.shape)
    #12/22/2025 note: I AM WORRIED THAT THERE IS DATA LOSS WHEN SWITCHING FROM NP ARRAYS BACK TO TENSORS THAT IS FUCKING UP RESULTS
    #https://www.tensorflow.org/tutorials/load_data/numpy <<---- need to read this later
    #Also I swear to god if ICE ever comes to UCA imma fight their asses. Fascists can go to hell. I'm getting drunk when dictator trump dies
    return self.row_num, combo, self.gold_label


  #https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean
  #https://www.kaggle.com/code/hughiephan/classification-with-mean-pooling-bert
  #https://stackoverflow.com/questions/76182289/how-does-average-pooling-function-work-in-tensorflow
  #https://www.youtube.com/watch?v=J5-DpRh_KPc
  #https://www.tensorflow.org/guide/tensor
  #https://stackoverflow.com/questions/53040412/alternative-to-global-pooling-using-tf-reduce-mean
  #12/22/2025 we pickle everything from the first file so the data necesary to do this should be there
  def get_mean_pool_embeds(self):
    last_hid_reduced_s1 = tf.math.reduce_mean(self.last_hid_state_s1, axis = 1)   #not sure if the axis should be 1 or 0 or none  --- it has to be 1
    last_hid_reduced_s2 = tf.math.reduce_mean(self.last_hid_state_s2, axis = 1)   #not sure if the axis should be 1 or 0 or none  ---- it has to be 1

    #I swear to God that I am missing a step here but I'll figure it out later, right now I need to drink a beer or eat a little debbie. 12/22/2025 @4:21pm

    hr1 = np.array(last_hid_reduced_s1)
    hr2 = np.array(last_hid_reduced_s2)

    combination = np.concatenate((hr1, hr2, np.abs(hr1 - hr2), hr1 * hr2), axis = 1)

    return self.row_num, combination, self.gold_label

  def get_mean_pool_embeds_joint(self):
    last_hid_reduced_joint = tf.math.reduce_mean(self.last_hid_state_joint, axis = 1)
    hrj = np.array(last_hid_reduced_joint)
    hrj = hrj[0]  #let's see if this addition changes performance
    return self.row_num, hrj, self.gold_label

  def get_cosine_sim_embed(self):
    last_hid_reduced_s1 = tf.math.reduce_mean(self.last_hid_state_s1, axis = 1)
    last_hid_reduced_s2 = tf.math.reduce_mean(self.last_hid_state_s2, axis = 1)

    hr1 = np.array(last_hid_reduced_s1)
    hr2 = np.array(last_hid_reduced_s2)

  def embed_joint_tensors(self):
    print("b") #it could be an issue of axis
    #http://tensorflow.org/guide/ragged_tensor
    #tensors can be ragged or dense, (models only accept dense) 1/11/2026 at 11:20pm
    self.tensorized_joint = self.tensorized_joint.to_tensor()
    self.embed_joint = bert_model(self.tensorized_joint, token_type_ids= self.token_type_ids.to_tensor()) #gonna try this 1/11/2026
    print("c")

  def last_hid_state_from_embed_joint(self):
    self.last_hid_state_joint = self.embed_joint.last_hidden_state

  def cls_embed_from_last_hid_state_joint(self):
    self.cls_embed_joint = self.last_hid_state_joint[:,0,:]

  def attention_mask(self):
    mask_s1 = tf.cast(self.pad_tensorized_s1 != 0, tf.int32)
    mask_s2 = tf.cast(self.pad_tensorized_s2 != 0, tf.int32)

    return mask_s1, mask_s2

  def joint_maker(self):
    #print("trying to make the joint at the flattened token level")
    #I need to remove the CLS of tensorized_s2 before putting them together
    def remove_CLS_from_tensorized_s2():
      CLS_ID = 101
      #print("1")

      cls_tok_id = tf.constant(CLS_ID, dtype = tf.int32)
      #print("2")

      mask = tf.not_equal(self.tensorized_s2, cls_tok_id)
      #print("3")

      #https://www.tensorflow.org/api_docs/python/tf/ragged/boolean_mask supposedly this does masking without fuckign things up
      self.tensorized_s2 = tf.ragged.boolean_mask(self.tensorized_s2, mask)
      #print("4")


    remove_CLS_from_tensorized_s2()
    #http://tensorflow.org/api_docs/python/tf/zeros_like token type ids are needed for the model to know that the two sentences in the joint are supposed to be interpreted as separate sentences
    s1_types = tf.zeros_like(self.tensorized_s1)
    s2_types = tf.ones_like(self.tensorized_s2)
    self.token_type_ids = tf.concat([s1_types, s2_types], axis=1)
    #joint_tokens = (["[CLS]"] + sent_1_tokens + ["[SEP]"] + sent_2_tokens + ["[SEP]"])
    #print("5")
    #https://www.geeksforgeeks.org/deep-learning/tensor-concatenations-in-tensorflow-with-example/ gonna go with axis = 0 (well idk)
    #self.tensorized_joint = tf.concat([self.tensorized_s1, self.tensorized_s2], axis = 0) #idk which axis I should do
    self.tensorized_joint = tf.concat([self.tensorized_s1, self.tensorized_s2], axis = 1) #idk which axis I should do
    #print("6")














# ___________________________________________________________________________
# ___________________________________________________________________________
# __________________________________________________________________________

def loadData(file_name):
  path = "/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval"
  #/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval/p_cs2.pkl
  #/content/drive/MyDrive/Colab Notebooks/DataforImportConcateEval/pcs2.pkl
  dbfile = open(path + '/' + file_name, 'rb')
  db = pickle.load(dbfile)
  dbfile.close
  return db

def pull_CLS(data_set):
  cls_data_set = []
  for entry in data_set:
    cls_data_set.append(entry.get_cls_embeds_rownum_concate_gold())
  return cls_data_set

def pull_CLS_joint(data_set):
  cls_data_set = []
  for entry in data_set:
    cls_data_set.append(entry.get_cls_embeds_rownum_concate_gold_joint())
  return cls_data_set

#12/22/2025 @10:33 pm I got a dentist appointment at the ass-crack of dawn tomorrow gotta code code code then snooze
def pull_mean_pool(data_set):
  mean_pool_data_set = []
  for entry in data_set:
    mean_pool_data_set.append(entry.get_mean_pool_embeds())
  return mean_pool_data_set

def pull_mean_pool_joint(data_set):
  mean_pool_data_set = []
  for entry in data_set:
    mean_pool_data_set.append(entry.get_mean_pool_embeds_joint())
  return mean_pool_data_set


#10/18/2025 we gonna add this to see if works now.
def pull_CLS_no_elemdiffpair(data_set):
  cls_data_set = []
  for entry in data_set:
    cls_data_set.append(entry.get_cls_embeds_no_elemdiffpair())
  return cls_data_set

def get_features_labels_ids(data_set): #features are the X, labels are the y, needed for sklearns training
  print("p")
  all_rownums = []   #the rownums
  all_features = []    #the cls combo
  all_labels = []     #the gold label

  for row in data_set:
    row_num, feature, label = row  #unpacks the tuple (literally, I had no clue I could do this)
    all_rownums.append(row_num)
    all_features.append(feature)
    all_labels.append(label)

  return all_rownums, all_features, all_labels  #shall be mapped properly


def mapping_checker(data_set, X, all_rownums, y):#will check shape by making sure that shape of X(i) = shape of pcs2(1)(i) and that row_num(i) = pcs2(2)(i)
  print("t")

  for i, (orig_rownum, orig_feature, orig_label) in enumerate(data_set):

    #makes sure row ids are in order
    if all_rownums[i] != orig_rownum:
      print(f"Row ID mismatch at index {i}: {all_rownums[i]} != {orig_rownum}")
    #checks to make sure features are properly mapped by looking at shape
    if not np.array_equal(X[i], orig_feature):
       print(f"THE CLSes ARE MISMATCHED!!!!!!!!!!!!!!!!!!!!!!! AT INDEX {i}")
    if not np.array_equal(y[i], orig_label):
      print(f"THE labels ARE MISMATCHED!!!!!!!!!!!!!!!!!!!!!!! AT INDEX {i}")

#takes the row ids of the original_data and the modified data
#then compares the two and checks which ones exist in the other
#then it goes and makes an new row_nums index that includes only a subset of row_nums in the og that DO NOT appear in modified row num list
#then it uses that new row_nums index as the mask to avoid training the sklearns on data that it should be tested on
#because og is for training, mod is for testing
#so og - mod = mask and mask is used for the training.
#https://www.programiz.com/python-programming/numpy/boolean-indexing
def masking_to_remove_hyphen_goldlabel(rows, features, labels):
  print("placeholder")

  rows = np.stack(rows)
  features = np.stack(features)
  labels = np.stack(labels)


  mask = (labels != '-')
  rows = rows[mask]
  features = features[mask]
  labels  = labels[mask]

  return rows, features, labels


'''
def masker_to_get_training_data(rows_og, rows_mod, features_og, labels_og):
  mask = ~np.isin(rows_og, rows_mod)
  features_og = np.stack(features_og)  #converts list of np arrays to 2d np array to make it so I can use the mask iterator
  labels_og = np.stack(labels_og)
  rows_og = np.stack(rows_og)


  Xtrain = features_og[mask]
  ytrain = labels_og[mask]
  rowtrain = rows_og[mask]

  return Xtrain, ytrain, rowtrain
'''
'''
#this trains the kfold classifier model X is the train features, y is the train labels, k is the number of folds
def train_stratifiedkfold_classifier_model(X, y, k):
  print("o")
  stratkfold = StratifiedKFold(n_splits = k, shuffle = True, random_state = 42)  #why the fuck does every online example use 42?
  accuracies = []
  f1s = []

  for fold, (train_index, eval_index) in enumerate(stratkfold.split(X, y)):
    X_train, X_eval = X[train_index], X[eval_index]
    y_train, y_eval = y[train_index], y[eval_index]

    #lg = logistic regression

    #teh logistic regression model itself
    classification_model = lg(max_iter = 1000)
    classification_model.fit(X_train, y_train)
    y_pred = classification_model.predict(X_eval)
    #this takes the model that was just trained, and makes it take a test. y_eval is the answer key, y_pred is the test
    accuracy = accuracy_score(y_eval, y_pred)
    f1 = f1_score(y_eval, y_pred, average = "weighted")

    accuracies.append(accuracy)
    f1s.append(f1)

  return classification_model, accuracies, f1s

'''

def label_encode(labels):
  print(type(labels[0]))
  le = LabelEncoder()
  labels_encoded = le.fit_transform(labels)
  print(type(labels_encoded[0]))
  return labels_encoded


def LOOCV_eval(model, X, y, scoring_method, cv):
  scores = cross_val_score(model, X, y, scoring = scoring_method, cv = cv , n_jobs= -1, verbose = 10)
  print(scores)
  return np.mean(scores), scores  #gonna do the np.mean instead  10/18/2025 at 3:08pm

def StratifiedKFold_eval(model, X, y, scoring_metrics, cv):
  print("placeholder to get rid off annoying ass error warning")
  scores = cross_validate(model, X, y, scoring = scoring_metrics, cv = cv, n_jobs = -1, verbose = 2)
  print(scores['test_accuracy'])
  print(scores['test_f1_macro'])
  return np.mean(scores['test_accuracy']), scores['test_accuracy'], np.mean(scores['test_f1_macro']), scores['test_f1_macro']

  #return np.mean(scores), scores

#puts results in text file
def gimme_results(mean_score, all_scores, file_name):
  #DO NOT USE THIS FUCTION
  folder_path = '/content/drive/MyDrive/Colab Notebooks/ResultsfromImportConcateEval'
  os.makedirs(folder_path, exist_ok = True) #makes the ding dang directory if I didn't already make it
  file_path = os.path.join(folder_path, file_name + ".txt")

  with open(file_path, 'w') as file:
    file.write(f"mean score of {file_name} : {mean_score}\n")
    file.write(f"all scores of {file_name} :\n {all_scores}\n")

def gimme_results_2(mean_score_accu, all_scores_accu, mean_score_f1_macro, all_scores_f1_macro, file_name, penalty, solver, l1_ratio, max_iter, C, n_components = None):
  #datetime
  #https://stackoverflow.com/questions/415511/how-do-i-get-the-current-time-in-python
  now = datetime.now()
  now_s = str(now)

  #change l1 ratio to string
  l1_string = str(l1_ratio)

  #change the n_components to string (for the experiment with dim reduction, when I need to print the results)
  n_components_string = str(n_components)
  max_iter_string = str(max_iter)
  C_string = str(C)

  folder_path = '/content/drive/MyDrive/Colab Notebooks/ResultsfromImportConcateEval'
  os.makedirs(folder_path, exist_ok = True) #makes the ding dang directory if I didn't already make it
  file_path = os.path.join(folder_path, file_name + "_penalty=" + penalty + "_solver=" + solver + "_l1_ratio=" + l1_string + "_" + "n_components_if_dim_reduction_" + n_components_string + "_max_iter=" + max_iter_string + "_" + "C_value=" + C_string + "_ " + now_s + ".txt")   #updated as of 12/22/2025 to get datetime in the file name


  with open(file_path, 'w') as file:
    file.write(f"mean accuracy score of {file_name} : {mean_score_accu}\n")
    file.write(f"all accuracy scores of {file_name} :\n {all_scores_accu}\n")
    file.write(f"mean f1_macro score of {file_name} : {mean_score_f1_macro}\n")
    file.write(f"all f1_macro scores of {file_name} :\n {all_scores_f1_macro}\n")


def doing_PCA(X, n_components):
  print("doing PCA for dim reduction")
  #the shape of X going in to this is (4167, 3072) where (4167 sentence pairings) and (3072 is the dimension of the feature rich concatenations)
  pca = PCA(n_components = n_components)  #als n_comoponents should be between 0 and 1
  X_pca = pca.fit_transform(X)    #<--- that motherfucking X must be scaled prior to being passed to doing_PCA()
  #https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html   There is a lotta fun shit I can do with this.

  return X_pca
  #gotta be real, I don't think I actually need this since I can just shove it into the pipeline


def preparing_data(pcs2, p_cs2):
  print("my back hurts")

  print(len(pcs2))   #unmodified
  print(len(p_cs2))   #modified


  #concatenates the data
   #as of 11/4/2025, turing this off so I can reduce the time it takes to calculate #as of 12/18/2025, I am turning this back on!
  e_pcs2 = pull_CLS(pcs2)
  print("\n-----\n")
  e_p_cs2 = pull_CLS(p_cs2)


  #12/22/2025 --- mean pool version
  pool_pcs2 = pull_mean_pool(pcs2)
  pool_p_cs2 = pull_mean_pool(p_cs2)


  print(e_pcs2[0])
  print(e_p_cs2[0])

  print(pool_pcs2[0])
  print(pool_p_cs2[0])


  row1, X1, y1 = get_features_labels_ids(e_pcs2)
  row2, X2, y2 = get_features_labels_ids(e_p_cs2)


  row5, X5, y5 = get_features_labels_ids(pool_pcs2)
  row6, X6, y6 = get_features_labels_ids(pool_p_cs2)

  mapping_checker(e_pcs2, X1, row1, y1)
  mapping_checker(e_p_cs2, X2, row2, y2)


  mapping_checker(pool_pcs2, X5, row5, y5)
  mapping_checker(pool_p_cs2, X6, row6, y6)



  row1, X1, y1 = masking_to_remove_hyphen_goldlabel(row1, X1, y1)
  row2, X2, y2 = masking_to_remove_hyphen_goldlabel(row2, X2, y2)



  row5, X5, y5 = masking_to_remove_hyphen_goldlabel(row5, X5, y5)
  row6, X6, y6 = masking_to_remove_hyphen_goldlabel(row6, X6, y6)

  #mapping_checker(e_og_p, Xogp, rowogp, yogp)

  #Xtrain, ytrain, rowtrain = masker_to_get_training_data(rowogp, row1, Xogp, yogp)

  #is good. There are 11 that get removed from Xtrain because the are already in pcs2/p_cs2 and we want no repeats
  #print(len(Xtrain))
  #print(len(Xogp))


  #clf_model, accuracies_og, f1s_og = train_stratifiedkfold_classifier_model(Xtrain, ytrain, 5) #sets k fold value to 5


  #Going to do the LOOCV instead


  print("values counter of y1 to y4")

  print(pd.Series(y1).value_counts())
  print(pd.Series(y2).value_counts())


  print(pd.Series(y5).value_counts())
  print(pd.Series(y6).value_counts())



  print(X1.shape)
  print(y1.shape)

  print(X5.shape)   #this this is 3d when it needs to be 2d, the middle dimension is 1. (4167, 1, 3072). I need to remove the middle dimension
  print(y5.shape)   #to do this, I must use tf.squeeze https://www.tensorflow.org/api_docs/python/tf/squeeze

  print(X6.shape)
  print(y6.shape)

  #if nececsary, I could move this into the actual class method instead to clean up this main function/have code reusability 12/27/2025
  #for now, gonna leave it in the main so I know that it is here.
  X5 = tf.squeeze(X5)
  X6 = tf.squeeze(X6)


  print(X5.shape)
  print(y5.shape)

  print(X6.shape)
  print(y6.shape)

  #the classification model below expects numpy arrays, and not tensorflow tensors ( i need to convert 5 and 6 (1 is already converted))

  X5 = np.array(X5)
  y5 = np.array(y5)

  X6 = np.array(X6)
  y6 = np.array(y6)

  encoder = LabelEncoder()
  encoder.fit(np.concatenate([y1, y2, y5, y6]))

  y1 = encoder.transform(y1)
  y2 = encoder.transform(y2)
  y5 = encoder.transform(y5)
  y6 = encoder.transform(y6)



  '''

  #encode the motherfucking labels! 12/28/2025

  y1 = label_encode(y1)
  y2 = label_encode(y2)

  y5 = label_encode(y5)
  y6 = label_encode(y6)
  '''


  '''
  1/7/2026 There is the potential that I am fucking up the labels here and instead should be doing
  encoder = LabelEncoder()
  encoder.fit(np.concatenate([y1, y2, y5, y6]))

  y1 = encoder.transform(y1)
  y2 = encoder.transform(y2)
  y5 = encoder.transform(y5)
  y6 = encoder.transform(y6)

  in order to prevent this
    CLS model:
    entailment → 0
    neutral    → 1
    contradiction → 2

  Mean-pool model:
    contradiction → 0
    entailment    → 1
    neutral       → 2


    #https://stackoverflow.com/questions/53735576/different-label-encoder-values-on-training-and-test-set-is-bad
    #https://stackoverflow.com/questions/31133192/usng-same-label-encoder-to-test-dataset-or-new-label-encoder
    yeah pretty sure this shit is wrong the way I currently have it.
  '''



  return X1, y1, X2, y2, X5, y5, X6, y6




  #_______________________________________________________________________________________#
  #_______________________________________________________________________________________#


def experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, penalty, solver, l1_ratio = None):
  print("placeholder")


  #12/22/2025 @10:57 note: https://stackoverflow.com/questions/38640109/logistic-regression-python-solvers-definitions I need to try these other solvers
  #https://scikit-learn.org/stable/modules/linear_model.html


  #classification_model = lg(max_iter= 1000)
  #12/28/2025 update: penalty and solver now input into the function; originally, this was liblinear with no penalty
  classification_model = pipe([('scaler', StandardScaler()), ('clf', lg(max_iter=5000, penalty = penalty, solver = solver, l1_ratio = l1_ratio ))]) #adding on lib linear to see if this helps 12/18/2025
  #as of 12/18/2025, I am abandoning the LOOCV for stratified k fold since my data set is now bigger
  cross_validation_method = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 42)
  scoring_metrics = ['accuracy', 'f1_macro'] #adding this in so I can get both!

  #chatgpt 10/18/2025 diagnosis of variance (little to no variance = bad)  but does it really? 12/18/2025 we gots good variance now

  print(np.mean(X1, axis=0)[:10])  # first 10 feature means
  print(np.std(X1, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X2, axis=0)[:10])  # first 10 feature means
  print(np.std(X2, axis=0)[:10])   # first 10 feature stds

  #12/22/2025 I ain't even goddam sure if this'll work for mean pool but gonna try it anyways if we get an error then we get a danmn error

  print(np.mean(X5, axis=0)[:10])  # first 10 feature means
  print(np.std(X5, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X6, axis=0)[:10])  # first 10 feature means
  print(np.std(X6, axis=0)[:10])   # first 10 feature stds


  #Stratified K Fold
  # _____________________________________________________________________________#

  #cls concatenations


  #unmodified
  mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X1, y1, scoring_metrics, cross_validation_method)
  print("mean_score_pcs2_accu: ")
  print(mean_score_pcs2_accu)
  print("mean_score_pcs2_f1_macro:")
  print(mean_score_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro, "UNMOD_CLS_results_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio)


  #modified
  mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X2, y2, scoring_metrics, cross_validation_method)
  print("mean_score_p_cs2_accu: ")
  print(mean_score_p_cs2_accu)
  print("mean_score_p_cs2_f1_macro: ")
  print(mean_score_p_cs2_f1_macro)


  #gimme_results(mean_score_noe_p_cs2, all_scores_noe_p_cs2, "results_noe_p_cs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro, "MOD_CLS_results_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio )



  #mean pool concatenations

  #unmodified
  mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X5, y5, scoring_metrics, cross_validation_method)
  print("mean_score_pool_pcs2_accu: ")
  print(mean_score_pool_pcs2_accu)
  print("mean_score_pool_pcs2_f1_macro:")
  print(mean_score_pool_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro, "UNMOD_MEANPOOL_results_pool_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio)


  #modified
  mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X6, y6, scoring_metrics, cross_validation_method)
  print("mean_score_pool_p_cs2_accu: ")
  print(mean_score_pool_p_cs2_accu)
  print("mean_score_pool_p_cs2_f1_macro:")
  print(mean_score_pool_p_cs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro, "MOD_MEANPOOL_results_pool_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio)

  #_______________________________________________________________________________________#
  #_______________________________________________________________________________________#


  return 1



def experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, penalty, solver, n_components, max_iter, C, l1_ratio = None):
  print("placeholder")


  #12/22/2025 @10:57 note: https://stackoverflow.com/questions/38640109/logistic-regression-python-solvers-definitions I need to try these other solvers
  #https://scikit-learn.org/stable/modules/linear_model.html


  #classification_model = lg(max_iter= 1000)
  #12/28/2025 update: penalty and solver now input into the function; originally, this was liblinear with no penalty
  classification_model = pipe([('scaler', StandardScaler()), ('pca', PCA(n_components = n_components)),  ('clf', lg(max_iter=max_iter, penalty = penalty, solver = solver, C = C,  l1_ratio = l1_ratio ))]) #adding on lib linear to see if this helps 12/18/2025
  #as of 12/18/2025, I am abandoning the LOOCV for stratified k fold since my data set is now bigger
  cross_validation_method = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 42)
  scoring_metrics = ['accuracy', 'f1_macro'] #adding this in so I can get both!

  #chatgpt 10/18/2025 diagnosis of variance (little to no variance = bad)  but does it really? 12/18/2025 we gots good variance now

  print(np.mean(X1, axis=0)[:10])  # first 10 feature means
  print(np.std(X1, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X2, axis=0)[:10])  # first 10 feature means
  print(np.std(X2, axis=0)[:10])   # first 10 feature stds

  #12/22/2025 I ain't even goddam sure if this'll work for mean pool but gonna try it anyways if we get an error then we get a danmn error

  print(np.mean(X5, axis=0)[:10])  # first 10 feature means
  print(np.std(X5, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X6, axis=0)[:10])  # first 10 feature means
  print(np.std(X6, axis=0)[:10])   # first 10 feature stds


  #Stratified K Fold
  # _____________________________________________________________________________#

  #cls concatenations


  #unmodified
  mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X1, y1, scoring_metrics, cross_validation_method)
  print("mean_score_pcs2_accu: ")
  print(mean_score_pcs2_accu)
  print("mean_score_pcs2_f1_macro:")
  print(mean_score_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro, "JOINT_UNMOD_CLS_results_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)


  #modified
  mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X2, y2, scoring_metrics, cross_validation_method)
  print("mean_score_p_cs2_accu: ")
  print(mean_score_p_cs2_accu)
  print("mean_score_p_cs2_f1_macro: ")
  print(mean_score_p_cs2_f1_macro)


  #gimme_results(mean_score_noe_p_cs2, all_scores_noe_p_cs2, "results_noe_p_cs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro, "JOINT_MOD_CLS_results_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components )



  #mean pool concatenations

  #unmodified
  mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X5, y5, scoring_metrics, cross_validation_method)
  print("mean_score_pool_pcs2_accu: ")
  print(mean_score_pool_pcs2_accu)
  print("mean_score_pool_pcs2_f1_macro:")
  print(mean_score_pool_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro, "JOINT_UNMOD_MEANPOOL_results_pool_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)


  #modified
  mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X6, y6, scoring_metrics, cross_validation_method)
  print("mean_score_pool_p_cs2_accu: ")
  print(mean_score_pool_p_cs2_accu)
  print("mean_score_pool_p_cs2_f1_macro:")
  print(mean_score_pool_p_cs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro, "JOINT_MOD_MEANPOOL_results_pool_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)

  #_______________________________________________________________________________________#
  #_______________________________________________________________________________________#


  return 2

def experiment_with_dim_reduction_but_scaling_afterPCA(X1, y1, X2, y2, X5, y5, X6, y6, penalty, solver, n_components, max_iter, C, l1_ratio = None):
  print("placeholder")


  #12/22/2025 @10:57 note: https://stackoverflow.com/questions/38640109/logistic-regression-python-solvers-definitions I need to try these other solvers
  #https://scikit-learn.org/stable/modules/linear_model.html


  #classification_model = lg(max_iter= 1000)
  #12/28/2025 update: penalty and solver now input into the function; originally, this was liblinear with no penalty
  classification_model = pipe([('pca', PCA(n_components = n_components)), ('scaler', StandardScaler()), ('clf', lg(max_iter=max_iter, penalty = penalty, solver = solver, C = C,  l1_ratio = l1_ratio ))]) #adding on lib linear to see if this helps 12/18/2025
  #as of 12/18/2025, I am abandoning the LOOCV for stratified k fold since my data set is now bigger
  cross_validation_method = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 42)
  scoring_metrics = ['accuracy', 'f1_macro'] #adding this in so I can get both!

  #chatgpt 10/18/2025 diagnosis of variance (little to no variance = bad)  but does it really? 12/18/2025 we gots good variance now

  print(np.mean(X1, axis=0)[:10])  # first 10 feature means
  print(np.std(X1, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X2, axis=0)[:10])  # first 10 feature means
  print(np.std(X2, axis=0)[:10])   # first 10 feature stds

  #12/22/2025 I ain't even goddam sure if this'll work for mean pool but gonna try it anyways if we get an error then we get a danmn error

  print(np.mean(X5, axis=0)[:10])  # first 10 feature means
  print(np.std(X5, axis=0)[:10])   # first 10 feature stds

  print(np.mean(X6, axis=0)[:10])  # first 10 feature means
  print(np.std(X6, axis=0)[:10])   # first 10 feature stds


  #Stratified K Fold
  # _____________________________________________________________________________#

  #cls concatenations


  #unmodified
  mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X1, y1, scoring_metrics, cross_validation_method)
  print("mean_score_pcs2_accu: ")
  print(mean_score_pcs2_accu)
  print("mean_score_pcs2_f1_macro:")
  print(mean_score_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pcs2_accu, all_scores_pcs2_accu, mean_score_pcs2_f1_macro, all_scores_pcs2_f1_macro, "AFTER_UNMOD_CLS_results_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)


  #modified
  mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X2, y2, scoring_metrics, cross_validation_method)
  print("mean_score_p_cs2_accu: ")
  print(mean_score_p_cs2_accu)
  print("mean_score_p_cs2_f1_macro: ")
  print(mean_score_p_cs2_f1_macro)


  #gimme_results(mean_score_noe_p_cs2, all_scores_noe_p_cs2, "results_noe_p_cs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_p_cs2_accu, all_scores_p_cs2_accu, mean_score_p_cs2_f1_macro, all_scores_p_cs2_f1_macro, "AFTER_MOD_CLS_results_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components )



  #mean pool concatenations

  #unmodified
  mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro = StratifiedKFold_eval(classification_model, X5, y5, scoring_metrics, cross_validation_method)
  print("mean_score_pool_pcs2_accu: ")
  print(mean_score_pool_pcs2_accu)
  print("mean_score_pool_pcs2_f1_macro:")
  print(mean_score_pool_pcs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_pcs2_accu, all_scores_pool_pcs2_accu, mean_score_pool_pcs2_f1_macro, all_scores_pool_pcs2_f1_macro, "AFTER_UNMOD_MEANPOOL_results_pool_pcs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)


  #modified
  mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro = StratifiedKFold_eval(classification_model, X6, y6, scoring_metrics, cross_validation_method)
  print("mean_score_pool_p_cs2_accu: ")
  print(mean_score_pool_p_cs2_accu)
  print("mean_score_pool_p_cs2_f1_macro:")
  print(mean_score_pool_p_cs2_f1_macro)

  #gimme_results(mean_score_noe_pcs2, all_scores_noe_pcs2, "results_noe_pcs2_StratifiedKFold_eval")
  gimme_results_2(mean_score_pool_p_cs2_accu, all_scores_pool_p_cs2_accu, mean_score_pool_p_cs2_f1_macro, all_scores_pool_p_cs2_f1_macro, "AFTER_MOD_MEANPOOL_results_pool_p_cs2_StratifiedKFold_eval", penalty, solver, l1_ratio, max_iter, C, n_components)

  #_______________________________________________________________________________________#
  #_______________________________________________________________________________________#


  return 3


#this motherfucking function is going to be called from inside the experiment_random_forest function 1/8/2026 I don't accutally need this function
def split_data_random_forest(X, y, test_size = 0.20, random_state = 42):
  print("placeholder 33 gimme some gottdawn vodka and a window pane!")
  #test_size is a default of 20% but can be changed if entered into function differently
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = test_size, random_state = random_state)
  return X_train, X_test, y_train, y_test


def make_classifier_random_forest(n_components, n_estimators, random_state):
  print("placeholder 44 gotta eat a bigmac and slap a man named Jimmy Gackerack!")
  classification_model = pipe([('scaler', StandardScaler()), ('pca', PCA(n_components = n_components)), ('clf', RandomForestClassifier(n_estimators = n_estimators, random_state = random_state))])
  return classification_model

def make_classifier_random_forest_PCA_then_Scale(n_components, n_estimators, random_state):
  print("placeholder 44 gotta eat a bigmac and slap a man named Jimmy Gackerack!")
  classification_model = pipe([('pca', PCA(n_components = n_components)), ('scaler', StandardScaler()), ('clf', RandomForestClassifier(n_estimators = n_estimators, random_state = random_state))])
  return classification_model

def make_classifier_random_forest_No_PCA(n_components, n_estimators, random_state):
  print("placeholder 44 gotta eat a bigmac and slap a man named Jimmy Gackerack!")
  classification_model = pipe([('scaler', StandardScaler()), ('clf', RandomForestClassifier(n_estimators = n_estimators, random_state = random_state))])
  return classification_model

def make_cross_validation_method():
  cross_validation_method = StratifiedKFold(n_splits = 10, shuffle = True, random_state = 42)
  return cross_validation_method

def make_scoring_metrics():
  scoring_metrics = ['accuracy', 'f1_macro'] #adding this in so I can get both!
  return scoring_metrics


def eval_random_forest(classification_model, X, y, scoring_metrics, cross_validation_method):
  mean_accu, all_accu, mean_f1, all_f1 = StratifiedKFold_eval(classification_model, X, y, scoring_metrics, cross_validation_method)
  print(f"{mean_accu}, {all_accu}, {mean_f1}, {all_f1}")
  return mean_accu, all_accu, mean_f1, all_f1

def tofile_rf(mean_accu, all_accu, mean_f1, all_f1, file_name, n_components, n_estimators, random_state):
  now = datetime.now()
  now_s = str(now)

  n_components_s = str(n_components)
  n_estimators_s = str(n_estimators)
  random_state_s = str(random_state)

  folder_path = '/content/drive/MyDrive/Colab Notebooks/ResultsfromImportConcateEval'
  os.makedirs(folder_path, exist_ok = True) #makes the ding dang directory if I didn't already make it
  file_path = os.path.join(folder_path, file_name + now_s +  ".txt")   #updated as of 12/22/2025 to get datetime in the file name


  with open(file_path, 'w') as file:
    file.write(f"n_components: {n_components_s}, n_estimators: {n_estimators_s}, random_state: {random_state_s}")
    file.write(f"mean accuracy score of {file_name} : {mean_accu}\n")
    file.write(f"all accuracy scores of {file_name} :\n {all_accu}\n")
    file.write(f"mean f1_macro score of {file_name} : {mean_f1}\n")
    file.write(f"all f1_macro scores of {file_name} :\n {all_f1}\n")

def experiment_random_forest(X5, y5, X6, y6, n_components, n_estimators, random_state):
  RFclf = make_classifier_random_forest(n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  cv = make_cross_validation_method()
  scrmet = make_scoring_metrics()
  unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1 = eval_random_forest(RFclf, X5, y5, scrmet, cv)
  mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1 = eval_random_forest(RFclf, X6, y6, scrmet, cv)

  tofile_rf(unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1, "unmod_random_forest", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  tofile_rf(mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1, "mod_random_forest", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  return 4

  '''
  classifier.fit(X_train, y_train)
  y_pred = classifier.predict(X_test)
  '''

def experiment_random_forest_PCA_then_Scale(X5, y5, X6, y6, n_components, n_estimators, random_state):
  RFclf = make_classifier_random_forest_PCA_then_Scale(n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  cv = make_cross_validation_method()
  scrmet = make_scoring_metrics()
  unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1 = eval_random_forest(RFclf, X5, y5, scrmet, cv)
  mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1 = eval_random_forest(RFclf, X6, y6, scrmet, cv)

  tofile_rf(unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1, "unmod_random_forest_PCA_then_Scale", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  tofile_rf(mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1, "mod_random_forest_PCA_then_Scale", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  return 5

def experiment_random_forest_No_PCA(X5, y5, X6, y6, n_components, n_estimators, random_state):
  RFclf = make_classifier_random_forest_No_PCA(n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  cv = make_cross_validation_method()
  scrmet = make_scoring_metrics()
  unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1 = eval_random_forest(RFclf, X5, y5, scrmet, cv)
  mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1 = eval_random_forest(RFclf, X6, y6, scrmet, cv)

  tofile_rf(unmod_mean_accu, unmod_all_accu, unmod_mean_f1, unmod_all_f1, "unmod_random_forest_No_PCA", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  tofile_rf(mod_mean_accu, mod_all_accu, mod_mean_f1, mod_all_f1, "mod_random_forest_No_PCA", n_components = n_components, n_estimators = n_estimators, random_state = random_state)
  return 6


def preparing_data_joint(pcs2, p_cs2):

  print(len(pcs2))   #unmodified
  print(len(p_cs2))   #modified


  #concatenates the data
   #as of 11/4/2025, turing this off so I can reduce the time it takes to calculate #as of 12/18/2025, I am turning this back on!
  e_pcs2 = pull_CLS_joint(pcs2)
  print("\n-----\n")
  e_p_cs2 = pull_CLS_joint(p_cs2)


  #12/22/2025 --- mean pool version
  pool_pcs2 = pull_mean_pool_joint(pcs2)
  pool_p_cs2 = pull_mean_pool_joint(p_cs2)


  print(e_pcs2[0])
  print(e_p_cs2[0])

  print(pool_pcs2[0])
  print(pool_p_cs2[0])


  row1, X1, y1 = get_features_labels_ids(e_pcs2)
  row2, X2, y2 = get_features_labels_ids(e_p_cs2)


  row5, X5, y5 = get_features_labels_ids(pool_pcs2)
  row6, X6, y6 = get_features_labels_ids(pool_p_cs2)

  mapping_checker(e_pcs2, X1, row1, y1)
  mapping_checker(e_p_cs2, X2, row2, y2)


  mapping_checker(pool_pcs2, X5, row5, y5)
  mapping_checker(pool_p_cs2, X6, row6, y6)



  row1, X1, y1 = masking_to_remove_hyphen_goldlabel(row1, X1, y1)
  row2, X2, y2 = masking_to_remove_hyphen_goldlabel(row2, X2, y2)



  row5, X5, y5 = masking_to_remove_hyphen_goldlabel(row5, X5, y5)
  row6, X6, y6 = masking_to_remove_hyphen_goldlabel(row6, X6, y6)




  print("values counter of y1 to y4")

  print(pd.Series(y1).value_counts())
  print(pd.Series(y2).value_counts())


  print(pd.Series(y5).value_counts())
  print(pd.Series(y6).value_counts())



  print(X1.shape)
  print(y1.shape)

  print(X5.shape)   #this this is 3d when it needs to be 2d, the middle dimension is 1. (4167, 1, 3072). I need to remove the middle dimension
  print(y5.shape)   #to do this, I must use tf.squeeze https://www.tensorflow.org/api_docs/python/tf/squeeze

  print(X6.shape)
  print(y6.shape)

  #if nececsary, I could move this into the actual class method instead to clean up this main function/have code reusability 12/27/2025
  #for now, gonna leave it in the main so I know that it is here.
  X5 = tf.squeeze(X5)
  X6 = tf.squeeze(X6)


  print(X5.shape)
  print(y5.shape)

  print(X6.shape)
  print(y6.shape)

  #the classification model below expects numpy arrays, and not tensorflow tensors ( i need to convert 5 and 6 (1 is already converted))

  X5 = np.array(X5)
  y5 = np.array(y5)

  X6 = np.array(X6)
  y6 = np.array(y6)

  encoder = LabelEncoder()
  encoder.fit(np.concatenate([y1, y2, y5, y6]))

  y1 = encoder.transform(y1)
  y2 = encoder.transform(y2)
  y5 = encoder.transform(y5)
  y6 = encoder.transform(y6)



  return X1, y1, X2, y2, X5, y5, X6, y6

#_____________________________________________________________________________#
#_____________________________________________________________________________#
#_____________________________________________________________________________#







def main():
  #loads the data from the pickle files
  print("ha")
  pcs2 = loadData("pcs2_13versionJointed.pkl")
  p_cs2 = loadData("p_cs2_13versionJointed.pkl")
  #og_set_partial = loadData("og_set.pkl")    #as of 10/5/2025, this is just the partial 500
  #update of 12/28/2025; I have split my main function into a prep data function and a run experiment function
  #update 1/12/2026, we are now smoking joints
  X1, y1, X2, y2, X5, y5, X6, y6 = preparing_data_joint(pcs2, p_cs2)

  #X1, y1, X2, y2, X5, y5, X6, y6 = preparing_data(pcs2, p_cs2)


  #update as of 12/28/25 all the shit that was originally in the main is now in its own function
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 1)
  #print(experiment_random_forest(X5, y5, X6, y6, n_components = 0.9, n_estimators = 100, random_state = 42))
  #print(experiment_random_forest_PCA_then_Scale(X5, y5, X6, y6, n_components = 0.9, n_estimators = 100, random_state = 42))  #<--- slightly better 1/8/2026 stick with this!


  #print(experiment_random_forest_PCA_then_Scale(X5, y5, X6, y6, n_components = 0.9, n_estimators = 200, random_state = 42))

  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l2", "saga", n_components = 0.90, max_iter = 200, C = 1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l2", "liblinear", n_components = 0.90, max_iter = 5000, C = 1)

  print(experiment_random_forest(X5, y5, X6, y6, n_components = 0.9, n_estimators = 100, random_state = 42))
  print(experiment_random_forest_PCA_then_Scale(X5, y5, X6, y6, n_components = 0.9, n_estimators = 500, random_state = 42))
  print(experiment_random_forest_No_PCA(X5, y5, X6, y6, n_components = 0.9, n_estimators = 500, random_state = 42))









  #print(experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 1))
  #print(experiment_with_dim_reduction_but_scaling_afterPCA(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 1))


  '''
  experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l2", "liblinear")
  experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga")
  experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l2", "saga")
  experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "elasticnet", "saga", l1_ratio = 0.5)
  '''

  '''
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 0.001)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 0.01)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 0.1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 10)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 100)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.90, max_iter = 5000, C = 1000)
  '''

  '''
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 0.001)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 0.01)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 0.1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 1)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 10)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 100)
  experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 200, C = 1000)
  '''



  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.99)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 1000)  #<---- 0.90 yeilds best for n_components
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 2000)  #<---- 0.90 yeilds best for n_components
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "saga", n_components = 0.90, max_iter = 1000)  #<---- 0.90 yeilds best for n_components
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.80)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.70)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.60)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.50)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.40)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.30)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.20)
  #experiment_with_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear", n_components = 0.10)



  #experiment_no_dim_reduction(X1, y1, X2, y2, X5, y5, X6, y6, "l1", "liblinear")


  #turns out I gotta add special shit do to the saga with (l1_ratio = 0.5) needs to be added into the lg() in the line that has the classifier model
  #so I'll need to make a separate goddam function for that 12/28/2025


  #https://www.geeksforgeeks.org/python/comparing-various-online-solvers-in-scikit-learn/
  #we are also gonna try various solvers
  #we could also change up the c_values
  #also various different solvers have different penalties.
  #12/28/2025 update: penalty and solver now input into the function; originally, this was liblinear with no penalty

  '''
                  penalties:
  solvers:          L1               L2               Elastic (L1+L2)

  lbfgs            fuck nah     hell yess               fuck nah               <--- only used on small data sets so I don't think this'll help


  liblinear       hell yess       hell yes              fuck no             <---- the one I have been trying but it kinda shit so far


  saga             hell yess       hell yes            hell yess                <---- sounds promising and I want to try it especially with elastic.

  sag               fuck no         hell yess             fuck nah

  there are some others but
  '''





if __name__ == "__main__":
  main()